import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = 
  | "en" 
  | "hi" 
  | "ta" 
  | "te" 
  | "bn" 
  | "mr" 
  | "gu" 
  | "kn" 
  | "ml" 
  | "pa" 
  | "or";

export const languageNames: Record<Language, string> = {
  en: "English",
  hi: "हिंदी",
  ta: "தமிழ்",
  te: "తెలుగు",
  bn: "বাংলা",
  mr: "मराठी",
  gu: "ગુજરાતી",
  kn: "ಕನ್ನಡ",
  ml: "മലയാളം",
  pa: "ਪੰਜਾਬੀ",
  or: "ଓଡ଼ିଆ",
};

type Translations = {
  // Home page
  cleanMarketInitiative: string;
  appName: string;
  tagline: string;
  getStarted: string;
  installApp: string;
  howItWorks: string;
  howItWorksDesc: string;
  vendorsUpload: string;
  vendorsUploadDesc: string;
  officersReview: string;
  officersReviewDesc: string;
  vendorsGetRanked: string;
  vendorsGetRankedDesc: string;
  readyToJoin: string;
  readyToJoinDesc: string;
  signUpNow: string;
  footer: string;
  selectLanguage: string;
  // Auth page
  login: string;
  signUp: string;
  welcomeBack: string;
  enterCredentials: string;
  createAccount: string;
  joinInitiative: string;
  email: string;
  password: string;
  fullName: string;
  iAmA: string;
  marketVendor: string;
  municipalityOfficer: string;
  marketName: string;
  loggingIn: string;
  creatingAccount: string;
  wasteManagementSystem: string;
  // Dashboard common
  logout: string;
  photosSubmitted: string;
  pointsThisWeek: string;
  currentStreak: string;
  weeklyRank: string;
  // Vendor Dashboard
  vendorDashboard: string;
  submitReport: string;
  rankings: string;
  reportStallStatus: string;
  reportStallStatusDesc: string;
  stallNumber: string;
  marketArea: string;
  selectArea: string;
  currentStatus: string;
  clean: string;
  needsCleaning: string;
  overflowing: string;
  comments: string;
  anyNotes: string;
  photoRequired: string;
  mySubmissions: string;
  noPhotosYet: string;
  pending: string;
  reviewed: string;
  cleaned: string;
  weeklyVendorRankings: string;
  pointsEarned: string;
  cleanReports: string;
  // Officer Dashboard
  municipalityDashboard: string;
  monitorManage: string;
  awaitingReview: string;
  underAction: string;
  completed: string;
  totalVendors: string;
  registered: string;
  photoReview: string;
  vendorRankings: string;
  marketPhotos: string;
  reviewManagePhotos: string;
  filterByStatus: string;
  allPhotos: string;
  filterByArea: string;
  allAreas: string;
  vendor: string;
  uploaded: string;
  score: string;
  markAsReviewed: string;
  markAsCleaned: string;
  noPhotosSubmitted: string;
  vendorsRankedByPoints: string;
  photos: string;
  points: string;
  // Market areas
  vegetablesSection: string;
  fruitsSection: string;
  flowerMarket: string;
  fishMarket: string;
  meatMarket: string;
  pathway: string;
  dustbinZone: string;
  other: string;
  // Additional translations
  stallPlaceholder: string;
  uploadSuccess: string;
  uploadError: string;
  pleaseUploadImage: string;
  fileSizeLimit: string;
  noAreaSpecified: string;
  pts: string;
  pt: string;
  unknownMarket: string;
  unknownVendor: string;
  failedToUpdateStatus: string;
  statusUpdatedTo: string;
  photoMarkedCleaned: string;
  photoMarkedReviewed: string;
  failedToMarkPhoto: string;
  failedToLoadRankings: string;
  failedToUpdateRankings: string;
  loading: string;
  loadMore: string;
  // Upload queue translations
  noInternet: string;
  uploadRetrying: string;
  uploadQueued: string;
  uploadFailed: string;
  retryUpload: string;
  retryAll: string;
  uploadingPhoto: string;
  queuedUploads: string;
  failedUploads: string;
  dismiss: string;
  offlineMode: string;
  willRetryWhenOnline: string;
  serverUnavailable: string;
  retryingAutomatically: string;
  retryCount: string;
  myReviews: string;
  noPendingPhotos: string;
  noReviewsYet: string;
};

const translations: Record<Language, Translations> = {
  en: {
    cleanMarketInitiative: "Clean Public Places Initiatives",
    appName: "UrbanEye AI",
    tagline: "AI-powered cleanliness monitoring for smarter cities",
    getStarted: "Get Started",
    installApp: "Install App",
    howItWorks: "How It Works",
    howItWorksDesc: "Computer vision meets civic action — three steps to cleaner public spaces",
    vendorsUpload: "Capture & Upload",
    vendorsUploadDesc: "People snap a photo and our AI instantly analyzes waste levels, type, and severity",
    officersReview: "AI-Assisted Review",
    officersReviewDesc: "Officers see AI-graded reports and dispatch cleaning crews to the highest-priority areas first",
    vendorsGetRanked: "Smart Rankings",
    vendorsGetRankedDesc: "AI-verified clean reports earn points — the most engaged person is crowned \"Cleanest Person of the Week\"",
    readyToJoin: "Ready to Join?",
    readyToJoinDesc: "Whether you're a person or a municipality officer, join the UrbanEye AI network today and help build smarter, cleaner cities.",
    signUpNow: "Sign Up Now",
    footer: "© 2026 UrbanEye AI. Transforming public spaces with intelligent waste detection.",
    selectLanguage: "Select Language",
    login: "Login",
    signUp: "Sign Up",
    welcomeBack: "Welcome Back",
    enterCredentials: "Enter your credentials to continue",
    createAccount: "Create Account",
    joinInitiative: "Join the UrbanEye AI network",
    email: "Email",
    password: "Password",
    fullName: "Full Name",
    iAmA: "I am a",
    marketVendor: "People",
    municipalityOfficer: "Municipality Officer",
    marketName: "Market Name",
    loggingIn: "Logging in...",
    creatingAccount: "Creating account...",
    wasteManagementSystem: "AI-powered cleanliness monitoring for smarter cities",
    logout: "Logout",
    photosSubmitted: "Photos Submitted",
    pointsThisWeek: "Points This Week",
    currentStreak: "Current Streak",
    weeklyRank: "Weekly Rank",
    vendorDashboard: "People Dashboard",
    submitReport: "Submit Report",
    rankings: "Rankings",
    reportStallStatus: "Report Stall Status",
    reportStallStatusDesc: "Select status and upload photo — municipal officers will review and grade.",
    stallNumber: "Stall Number",
    marketArea: "Market Area",
    selectArea: "Select area...",
    currentStatus: "Current Status",
    clean: "Clean",
    needsCleaning: "Needs Cleaning",
    overflowing: "Overflowing",
    comments: "Comments",
    anyNotes: "Any notes...",
    photoRequired: "Photo Required — Click to upload",
    mySubmissions: "My Submissions",
    noPhotosYet: "No photos yet",
    pending: "Pending",
    reviewed: "Reviewed",
    cleaned: "Cleaned",
    weeklyVendorRankings: "Weekly People Rankings",
    pointsEarned: "Points earned this week",
    cleanReports: "clean reports",
    municipalityDashboard: "Municipality Dashboard",
    monitorManage: "Monitor and manage market cleanliness",
    awaitingReview: "Awaiting review",
    underAction: "Under action",
    completed: "Completed",
    totalVendors: "Total People",
    registered: "Registered",
    photoReview: "Photo Review",
    vendorRankings: "People Rankings",
    marketPhotos: "Market Photos",
    reviewManagePhotos: "Review and manage submitted photos",
    filterByStatus: "Filter by status",
    allPhotos: "All Photos",
    filterByArea: "Filter by area",
    allAreas: "All Areas",
    vendor: "People",
    uploaded: "Uploaded",
    score: "Score",
    markAsReviewed: "Mark as Reviewed",
    markAsCleaned: "Mark as Cleaned",
    noPhotosSubmitted: "No photos submitted yet.",
    vendorsRankedByPoints: "People ranked by total points earned this week",
    photos: "photos",
    points: "points",
    vegetablesSection: "Vegetables Section",
    fruitsSection: "Fruits Section",
    flowerMarket: "Flower Market",
    fishMarket: "Fish Market",
    meatMarket: "Meat Market",
    pathway: "Pathway",
    dustbinZone: "Dustbin Zone",
    other: "Other",
    stallPlaceholder: "e.g., A-12",
    uploadSuccess: "Thanks — your report has been recorded. Municipal review pending.",
    uploadError: "Error uploading photo",
    pleaseUploadImage: "Please upload an image file",
    fileSizeLimit: "File size must be less than 5MB",
    noAreaSpecified: "No area specified",
    pts: "pts",
    pt: "pt",
    unknownMarket: "Unknown Market",
    unknownVendor: "Unknown",
    failedToUpdateStatus: "Failed to update status",
    statusUpdatedTo: "Status updated to",
    photoMarkedCleaned: "Photo marked as cleaned - Person awarded +1 point",
    photoMarkedReviewed: "Photo marked as reviewed - No points awarded",
    failedToMarkPhoto: "Failed to mark photo",
    failedToLoadRankings: "Failed to load rankings",
    failedToUpdateRankings: "Failed to update rankings",
    loading: "Loading...",
    loadMore: "Load More",
    noInternet: "No internet connection",
    uploadRetrying: "Retrying upload...",
    uploadQueued: "Upload queued",
    uploadFailed: "Upload failed",
    retryUpload: "Retry",
    retryAll: "Retry All",
    uploadingPhoto: "Uploading photo...",
    queuedUploads: "uploads queued",
    failedUploads: "uploads failed",
    dismiss: "Dismiss",
    offlineMode: "Offline Mode",
    willRetryWhenOnline: "Will retry when online",
    serverUnavailable: "Server unavailable",
    retryingAutomatically: "Retrying automatically...",
    retryCount: "Retries",
    myReviews: "My Reviews",
    noPendingPhotos: "No pending photos to review",
    noReviewsYet: "You haven't reviewed any photos yet",
  },
  hi: {
    cleanMarketInitiative: "स्वच्छ बाज़ार पहल",
    appName: "UrbanEye AI",
    tagline: "स्वच्छ, स्वस्थ सार्वजनिक बाज़ारों के लिए विक्रेताओं को अधिकारियों से जोड़ने वाली नगरपालिका अपशिष्ट प्रबंधन प्रणाली",
    getStarted: "शुरू करें",
    installApp: "ऐप इंस्टॉल करें",
    howItWorks: "यह कैसे काम करता है",
    howItWorksDesc: "बाज़ार की स्वच्छता बनाए रखने की एक सरल तीन-चरण प्रक्रिया",
    vendorsUpload: "विक्रेता अपलोड करें",
    vendorsUploadDesc: "बाज़ार के विक्रेता अपने क्षेत्रों की तस्वीरें लेते हैं और कचरे की रिपोर्ट करने या स्वच्छता प्रदर्शित करने के लिए छवियां अपलोड करते हैं",
    officersReview: "अधिकारी समीक्षा करें",
    officersReviewDesc: "नगरपालिका अधिकारी प्रस्तुतियों की समीक्षा करते हैं और जिन क्षेत्रों पर ध्यान देने की आवश्यकता है वहां सफाई दल भेजते हैं",
    vendorsGetRanked: "विक्रेताओं की रैंकिंग",
    vendorsGetRankedDesc: "सक्रिय विक्रेताओं को साप्ताहिक रैंक किया जाता है, सबसे सक्रिय विक्रेता को \"सप्ताह का स्वच्छ विक्रेता\" का ताज पहनाया जाता है",
    readyToJoin: "जुड़ने के लिए तैयार?",
    readyToJoinDesc: "चाहे आप बाज़ार के विक्रेता हों या नगरपालिका अधिकारी, आज ही मार्केटसेंस से जुड़ें और स्वच्छ, स्वस्थ सार्वजनिक स्थानों में योगदान करें।",
    signUpNow: "अभी साइन अप करें",
    footer: "© 2024 मार्केटसेंस। मिलकर स्वच्छ समुदाय बनाना।",
    selectLanguage: "भाषा चुनें",
    login: "लॉगिन",
    signUp: "साइन अप",
    welcomeBack: "वापस स्वागत है",
    enterCredentials: "जारी रखने के लिए अपना विवरण दर्ज करें",
    createAccount: "खाता बनाएं",
    joinInitiative: "मार्केटसेंस पहल से जुड़ें",
    email: "ईमेल",
    password: "पासवर्ड",
    fullName: "पूरा नाम",
    iAmA: "मैं हूं",
    marketVendor: "बाज़ार विक्रेता",
    municipalityOfficer: "नगरपालिका अधिकारी",
    marketName: "बाज़ार का नाम",
    loggingIn: "लॉगिन हो रहा है...",
    creatingAccount: "खाता बन रहा है...",
    wasteManagementSystem: "सार्वजनिक बाज़ारों के लिए अपशिष्ट प्रबंधन प्रणाली",
    logout: "लॉगआउट",
    photosSubmitted: "फोटो जमा किए गए",
    pointsThisWeek: "इस सप्ताह के अंक",
    currentStreak: "वर्तमान स्ट्रीक",
    weeklyRank: "साप्ताहिक रैंक",
    vendorDashboard: "विक्रेता डैशबोर्ड",
    submitReport: "रिपोर्ट जमा करें",
    rankings: "रैंकिंग",
    reportStallStatus: "स्टॉल की स्थिति रिपोर्ट करें",
    reportStallStatusDesc: "स्थिति चुनें और फोटो अपलोड करें — नगरपालिका अधिकारी समीक्षा करेंगे।",
    stallNumber: "स्टॉल नंबर",
    marketArea: "बाज़ार क्षेत्र",
    selectArea: "क्षेत्र चुनें...",
    currentStatus: "वर्तमान स्थिति",
    clean: "स्वच्छ",
    needsCleaning: "सफाई चाहिए",
    overflowing: "ओवरफ्लो",
    comments: "टिप्पणियां",
    anyNotes: "कोई नोट्स...",
    photoRequired: "फोटो आवश्यक — अपलोड करने के लिए क्लिक करें",
    mySubmissions: "मेरी प्रस्तुतियां",
    noPhotosYet: "अभी तक कोई फोटो नहीं",
    pending: "लंबित",
    reviewed: "समीक्षित",
    cleaned: "साफ किया",
    weeklyVendorRankings: "साप्ताहिक विक्रेता रैंकिंग",
    pointsEarned: "इस सप्ताह अर्जित अंक",
    cleanReports: "स्वच्छ रिपोर्ट",
    municipalityDashboard: "नगरपालिका डैशबोर्ड",
    monitorManage: "बाज़ार स्वच्छता की निगरानी और प्रबंधन करें",
    awaitingReview: "समीक्षा की प्रतीक्षा",
    underAction: "कार्रवाई में",
    completed: "पूर्ण",
    totalVendors: "कुल विक्रेता",
    registered: "पंजीकृत",
    photoReview: "फोटो समीक्षा",
    vendorRankings: "विक्रेता रैंकिंग",
    marketPhotos: "बाज़ार फोटो",
    reviewManagePhotos: "जमा फोटो की समीक्षा और प्रबंधन करें",
    filterByStatus: "स्थिति से फ़िल्टर करें",
    allPhotos: "सभी फोटो",
    filterByArea: "क्षेत्र से फ़िल्टर करें",
    allAreas: "सभी क्षेत्र",
    vendor: "विक्रेता",
    uploaded: "अपलोड किया",
    score: "स्कोर",
    markAsReviewed: "समीक्षित के रूप में चिह्नित करें",
    markAsCleaned: "साफ के रूप में चिह्नित करें",
    noPhotosSubmitted: "अभी तक कोई फोटो जमा नहीं हुई।",
    vendorsRankedByPoints: "इस सप्ताह अर्जित कुल अंकों द्वारा विक्रेताओं की रैंकिंग",
    photos: "फोटो",
    points: "अंक",
    vegetablesSection: "सब्जी अनुभाग",
    fruitsSection: "फल अनुभाग",
    flowerMarket: "फूल बाज़ार",
    fishMarket: "मछली बाज़ार",
    meatMarket: "मांस बाज़ार",
    pathway: "मार्ग",
    dustbinZone: "कूड़ेदान क्षेत्र",
    other: "अन्य",
    stallPlaceholder: "उदा., A-12",
    uploadSuccess: "धन्यवाद — आपकी रिपोर्ट दर्ज हो गई है। नगरपालिका समीक्षा लंबित।",
    uploadError: "फोटो अपलोड करने में त्रुटि",
    pleaseUploadImage: "कृपया एक छवि फ़ाइल अपलोड करें",
    fileSizeLimit: "फ़ाइल का आकार 5MB से कम होना चाहिए",
    noAreaSpecified: "कोई क्षेत्र निर्दिष्ट नहीं",
    pts: "अंक",
    pt: "अंक",
    unknownMarket: "अज्ञात बाज़ार",
    unknownVendor: "अज्ञात",
    failedToUpdateStatus: "स्थिति अपडेट करने में विफल",
    statusUpdatedTo: "स्थिति अपडेट हुई",
    photoMarkedCleaned: "फोटो साफ के रूप में चिह्नित — विक्रेता को +1 अंक मिला",
    photoMarkedReviewed: "फोटो समीक्षित के रूप में चिह्नित — कोई अंक नहीं",
    failedToMarkPhoto: "फोटो चिह्नित करने में विफल",
    failedToLoadRankings: "रैंकिंग लोड करने में विफल",
    failedToUpdateRankings: "रैंकिंग अपडेट करने में विफल",
    loading: "लोड हो रहा है...",
    loadMore: "और लोड करें",
    noInternet: "इंटरनेट कनेक्शन नहीं",
    uploadRetrying: "अपलोड पुनः प्रयास हो रहा है...",
    uploadQueued: "अपलोड कतार में",
    uploadFailed: "अपलोड विफल",
    retryUpload: "पुनः प्रयास",
    retryAll: "सभी पुनः प्रयास करें",
    uploadingPhoto: "फोटो अपलोड हो रहा है...",
    queuedUploads: "अपलोड कतार में हैं",
    failedUploads: "अपलोड विफल हुए",
    dismiss: "खारिज करें",
    offlineMode: "ऑफलाइन मोड",
    willRetryWhenOnline: "ऑनलाइन होने पर पुनः प्रयास होगा",
    serverUnavailable: "सर्वर अनुपलब्ध",
    retryingAutomatically: "स्वचालित रूप से पुनः प्रयास हो रहा है...",
    retryCount: "पुनः प्रयास",
    myReviews: "मेरी समीक्षाएँ",
    noPendingPhotos: "समीक्षा के लिए कोई लंबित फोटो नहीं",
    noReviewsYet: "आपने अभी तक कोई फोटो समीक्षा नहीं की है",
  },
  ta: {
    cleanMarketInitiative: "சுத்தமான சந்தை முன்முயற்சி",
    appName: "UrbanEye AI",
    tagline: "சுத்தமான, ஆரோக்கியமான பொது சந்தைகளுக்கு விற்பனையாளர்களை அதிகாரிகளுடன் இணைக்கும் நகராட்சி கழிவு மேலாண்மை அமைப்பு",
    getStarted: "தொடங்குங்கள்",
    installApp: "பயன்பாட்டை நிறுவு",
    howItWorks: "இது எப்படி வேலை செய்கிறது",
    howItWorksDesc: "சந்தை சுத்தத்தை பராமரிக்க ஒரு எளிய மூன்று-படி செயல்முறை",
    vendorsUpload: "விற்பனையாளர்கள் பதிவேற்றம்",
    vendorsUploadDesc: "சந்தை விற்பனையாளர்கள் தங்கள் பகுதிகளை புகைப்படம் எடுத்து கழிவுகளை புகாரளிக்க அல்லது சுத்தத்தை காட்சிப்படுத்த படங்களை பதிவேற்றுகிறார்கள்",
    officersReview: "அதிகாரிகள் மதிப்பாய்வு",
    officersReviewDesc: "நகராட்சி அதிகாரிகள் சமர்ப்பிப்புகளை மதிப்பாய்வு செய்து கவனிக்க வேண்டிய பகுதிகளுக்கு சுத்தம் செய்யும் குழுக்களை அனுப்புகிறார்கள்",
    vendorsGetRanked: "விற்பனையாளர்கள் தரவரிசைப்படுத்தப்படுகிறார்கள்",
    vendorsGetRankedDesc: "செயலில் உள்ள விற்பனையாளர்கள் வாராந்திர தரவரிசை பெறுகிறார்கள், மிகவும் ஈடுபாடுள்ள விற்பனையாளர் \"வாரத்தின் சுத்தமான விற்பனையாளர்\" பட்டம் பெறுகிறார்",
    readyToJoin: "சேர தயாரா?",
    readyToJoinDesc: "நீங்கள் சந்தை விற்பனையாளராக இருந்தாலும் நகராட்சி அதிகாரியாக இருந்தாலும், இன்றே மார்க்கெட்சென்ஸில் சேர்ந்து சுத்தமான, ஆரோக்கியமான பொது இடங்களுக்கு பங்களிக்கவும்.",
    signUpNow: "இப்போதே பதிவு செய்யுங்கள்",
    footer: "© 2024 மார்க்கெட்சென்ஸ். ஒன்றாக சுத்தமான சமூகங்களை உருவாக்குதல்.",
    selectLanguage: "மொழியைத் தேர்ந்தெடுக்கவும்",
    login: "உள்நுழை",
    signUp: "பதிவு செய்",
    welcomeBack: "மீண்டும் வரவேற்கிறோம்",
    enterCredentials: "தொடர உங்கள் விவரங்களை உள்ளிடவும்",
    createAccount: "கணக்கை உருவாக்கு",
    joinInitiative: "மார்க்கெட்சென்ஸ் முன்முயற்சியில் சேரவும்",
    email: "மின்னஞ்சல்",
    password: "கடவுச்சொல்",
    fullName: "முழு பெயர்",
    iAmA: "நான் ஒரு",
    marketVendor: "சந்தை விற்பனையாளர்",
    municipalityOfficer: "நகராட்சி அதிகாரி",
    marketName: "சந்தை பெயர்",
    loggingIn: "உள்நுழைகிறது...",
    creatingAccount: "கணக்கு உருவாக்கப்படுகிறது...",
    wasteManagementSystem: "பொது சந்தைகளுக்கான கழிவு மேலாண்மை அமைப்பு",
    logout: "வெளியேறு",
    photosSubmitted: "சமர்ப்பிக்கப்பட்ட புகைப்படங்கள்",
    pointsThisWeek: "இந்த வாரம் புள்ளிகள்",
    currentStreak: "தற்போதைய தொடர்",
    weeklyRank: "வாராந்திர தரவரிசை",
    vendorDashboard: "விற்பனையாளர் டாஷ்போர்டு",
    submitReport: "அறிக்கை சமர்ப்பி",
    rankings: "தரவரிசைகள்",
    reportStallStatus: "கடை நிலையை புகாரளி",
    reportStallStatusDesc: "நிலையைத் தேர்ந்தெடுத்து புகைப்படம் பதிவேற்றவும் — நகராட்சி அதிகாரிகள் மதிப்பாய்வு செய்வார்கள்.",
    stallNumber: "கடை எண்",
    marketArea: "சந்தை பகுதி",
    selectArea: "பகுதியைத் தேர்ந்தெடுக்கவும்...",
    currentStatus: "தற்போதைய நிலை",
    clean: "சுத்தமான",
    needsCleaning: "சுத்தம் தேவை",
    overflowing: "நிரம்பி வழிகிறது",
    comments: "கருத்துகள்",
    anyNotes: "ஏதேனும் குறிப்புகள்...",
    photoRequired: "புகைப்படம் தேவை — பதிவேற்ற கிளிக் செய்யவும்",
    mySubmissions: "என் சமர்ப்பிப்புகள்",
    noPhotosYet: "இன்னும் புகைப்படங்கள் இல்லை",
    pending: "நிலுவையில்",
    reviewed: "மதிப்பாய்வு செய்யப்பட்டது",
    cleaned: "சுத்தம் செய்யப்பட்டது",
    weeklyVendorRankings: "வாராந்திர விற்பனையாளர் தரவரிசைகள்",
    pointsEarned: "இந்த வாரம் பெற்ற புள்ளிகள்",
    cleanReports: "சுத்தமான அறிக்கைகள்",
    municipalityDashboard: "நகராட்சி டாஷ்போர்டு",
    monitorManage: "சந்தை சுத்தத்தை கண்காணித்து நிர்வகிக்கவும்",
    awaitingReview: "மதிப்பாய்வுக்கு காத்திருக்கிறது",
    underAction: "நடவடிக்கையில்",
    completed: "முடிந்தது",
    totalVendors: "மொத்த விற்பனையாளர்கள்",
    registered: "பதிவுசெய்யப்பட்டது",
    photoReview: "புகைப்பட மதிப்பாய்வு",
    vendorRankings: "விற்பனையாளர் தரவரிசைகள்",
    marketPhotos: "சந்தை புகைப்படங்கள்",
    reviewManagePhotos: "சமர்ப்பிக்கப்பட்ட புகைப்படங்களை மதிப்பாய்வு செய்து நிர்வகிக்கவும்",
    filterByStatus: "நிலை மூலம் வடிகட்டு",
    allPhotos: "அனைத்து புகைப்படங்கள்",
    filterByArea: "பகுதி மூலம் வடிகட்டு",
    allAreas: "அனைத்து பகுதிகள்",
    vendor: "விற்பனையாளர்",
    uploaded: "பதிவேற்றப்பட்டது",
    score: "மதிப்பெண்",
    markAsReviewed: "மதிப்பாய்வு செய்ததாக குறி",
    markAsCleaned: "சுத்தம் செய்ததாக குறி",
    noPhotosSubmitted: "இன்னும் புகைப்படங்கள் சமர்ப்பிக்கப்படவில்லை.",
    vendorsRankedByPoints: "இந்த வாரம் பெற்ற மொத்த புள்ளிகளின் அடிப்படையில் விற்பனையாளர்கள் தரவரிசைப்படுத்தப்பட்டுள்ளனர்",
    photos: "புகைப்படங்கள்",
    points: "புள்ளிகள்",
    vegetablesSection: "காய்கறி பிரிவு",
    fruitsSection: "பழம் பிரிவு",
    flowerMarket: "மலர் சந்தை",
    fishMarket: "மீன் சந்தை",
    meatMarket: "இறைச்சி சந்தை",
    pathway: "நடைபாதை",
    dustbinZone: "குப்பைத்தொட்டி பகுதி",
    other: "மற்றவை",
    stallPlaceholder: "எ.கா., A-12",
    uploadSuccess: "நன்றி — உங்கள் அறிக்கை பதிவு செய்யப்பட்டது. நகராட்சி மதிப்பாய்வு நிலுவையில்.",
    uploadError: "புகைப்படம் பதிவேற்றுவதில் பிழை",
    pleaseUploadImage: "படக் கோப்பை பதிவேற்றவும்",
    fileSizeLimit: "கோப்பு அளவு 5MB-க்கும் குறைவாக இருக்க வேண்டும்",
    noAreaSpecified: "பகுதி குறிப்பிடப்படவில்லை",
    pts: "புள்ளிகள்",
    pt: "புள்ளி",
    unknownMarket: "அறியப்படாத சந்தை",
    unknownVendor: "அறியப்படாதது",
    failedToUpdateStatus: "நிலையை புதுப்பிக்க முடியவில்லை",
    statusUpdatedTo: "நிலை புதுப்பிக்கப்பட்டது",
    photoMarkedCleaned: "புகைப்படம் சுத்தமாக குறிக்கப்பட்டது — விற்பனையாளருக்கு +1 புள்ளி",
    photoMarkedReviewed: "புகைப்படம் மதிப்பாய்வு செய்யப்பட்டதாக குறிக்கப்பட்டது — புள்ளிகள் இல்லை",
    failedToMarkPhoto: "புகைப்படத்தை குறிக்க முடியவில்லை",
    failedToLoadRankings: "தரவரிசைகளை ஏற்ற முடியவில்லை",
    failedToUpdateRankings: "தரவரிசைகளை புதுப்பிக்க முடியவில்லை",
    loading: "ஏற்றுகிறது...",
    loadMore: "மேலும் ஏற்றவும்",
    noInternet: "இணைய இணைப்பு இல்லை",
    uploadRetrying: "பதிவேற்றம் மீண்டும் முயற்சிக்கிறது...",
    uploadQueued: "பதிவேற்றம் வரிசையில்",
    uploadFailed: "பதிவேற்றம் தோல்வி",
    retryUpload: "மீண்டும் முயற்சி",
    retryAll: "அனைத்தையும் மீண்டும் முயற்சி",
    uploadingPhoto: "புகைப்படம் பதிவேற்றுகிறது...",
    queuedUploads: "பதிவேற்றங்கள் வரிசையில்",
    failedUploads: "பதிவேற்றங்கள் தோல்வி",
    dismiss: "நிராகரி",
    offlineMode: "ஆஃப்லைன் முறை",
    willRetryWhenOnline: "ஆன்லைனில் இருக்கும்போது மீண்டும் முயற்சிக்கும்",
    serverUnavailable: "சேவையகம் கிடைக்கவில்லை",
    retryingAutomatically: "தானாக மீண்டும் முயற்சிக்கிறது...",
    retryCount: "மறு முயற்சிகள்",
    myReviews: "என் மதிப்புரைகள்",
    noPendingPhotos: "மதிப்பாய்வு செய்ய நிலுவையில் உள்ள புகைப்படங்கள் இல்லை",
    noReviewsYet: "நீங்கள் இன்னும் எந்த புகைப்படங்களையும் மதிப்பாய்வு செய்யவில்லை",
  },
  te: {
    cleanMarketInitiative: "స్వచ్ఛ మార్కెట్ చొరవ",
    appName: "UrbanEye AI",
    tagline: "శుభ్రమైన, ఆరోగ్యకరమైన పబ్లిక్ మార్కెట్ల కోసం విక్రేతలను అధికారులతో అనుసంధానం చేసే మున్సిపల్ వ్యర్థ నిర్వహణ వ్యవస్థ",
    getStarted: "ప్రారంభించండి",
    installApp: "యాప్ ఇన్‌స్టాల్ చేయండి",
    howItWorks: "ఇది ఎలా పని చేస్తుంది",
    howItWorksDesc: "మార్కెట్ పరిశుభ్రతను నిర్వహించడానికి సరళమైన మూడు-దశల ప్రక్రియ",
    vendorsUpload: "విక్రేతలు అప్‌లోడ్ చేయండి",
    vendorsUploadDesc: "మార్కెట్ విక్రేతలు తమ ప్రాంతాలను ఫోటో తీసి వ్యర్థాలను నివేదించడానికి లేదా పరిశుభ్రతను ప్రదర్శించడానికి చిత్రాలను అప్‌లోడ్ చేస్తారు",
    officersReview: "అధికారులు సమీక్షించండి",
    officersReviewDesc: "మున్సిపాలిటీ అధికారులు సమర్పణలను సమీక్షించి శ్రద్ధ అవసరమైన ప్రాంతాలకు క్లీనింగ్ సిబ్బందిని పంపుతారు",
    vendorsGetRanked: "విక్రేతలు ర్యాంక్ పొందుతారు",
    vendorsGetRankedDesc: "యాక్టివ్ విక్రేతలు వారంతపు ర్యాంకింగ్ పొందుతారు, అత్యంత చురుకైన విక్రేతకు \"వారపు స్వచ్ఛ విక్రేత\" బిరుదం లభిస్తుంది",
    readyToJoin: "చేరడానికి సిద్ధంగా ఉన్నారా?",
    readyToJoinDesc: "మీరు మార్కెట్ విక్రేత అయినా లేదా మున్సిపాలిటీ అధికారి అయినా, ఈ రోజే మార్కెట్‌సెన్స్‌లో చేరండి మరియు శుభ్రమైన, ఆరోగ్యకరమైన పబ్లిక్ స్థలాలకు సహకరించండి.",
    signUpNow: "ఇప్పుడే సైన్ అప్ చేయండి",
    footer: "© 2024 మార్కెట్‌సెన్స్. కలిసి శుభ్రమైన సమాజాలను నిర్మించడం.",
    selectLanguage: "భాషను ఎంచుకోండి",
    login: "లాగిన్",
    signUp: "సైన్ అప్",
    welcomeBack: "తిరిగి స్వాగతం",
    enterCredentials: "కొనసాగించడానికి మీ వివరాలను నమోదు చేయండి",
    createAccount: "ఖాతా సృష్టించండి",
    joinInitiative: "మార్కెట్‌సెన్స్ చొరవలో చేరండి",
    email: "ఇమెయిల్",
    password: "పాస్‌వర్డ్",
    fullName: "పూర్తి పేరు",
    iAmA: "నేను ఒక",
    marketVendor: "మార్కెట్ విక్రేత",
    municipalityOfficer: "మున్సిపాలిటీ అధికారి",
    marketName: "మార్కెట్ పేరు",
    loggingIn: "లాగిన్ అవుతోంది...",
    creatingAccount: "ఖాతా సృష్టిస్తోంది...",
    wasteManagementSystem: "పబ్లిక్ మార్కెట్ల కోసం వ్యర్థ నిర్వహణ వ్యవస్థ",
    logout: "లాగౌట్",
    photosSubmitted: "సమర్పించిన ఫోటోలు",
    pointsThisWeek: "ఈ వారం పాయింట్లు",
    currentStreak: "ప్రస్తుత స్ట్రీక్",
    weeklyRank: "వారపు ర్యాంక్",
    vendorDashboard: "విక్రేత డాష్‌బోర్డ్",
    submitReport: "నివేదిక సమర్పించండి",
    rankings: "ర్యాంకింగ్‌లు",
    reportStallStatus: "స్టాల్ స్థితిని నివేదించండి",
    reportStallStatusDesc: "స్థితిని ఎంచుకుని ఫోటో అప్‌లోడ్ చేయండి — మున్సిపల్ అధికారులు సమీక్షిస్తారు.",
    stallNumber: "స్టాల్ నంబర్",
    marketArea: "మార్కెట్ ప్రాంతం",
    selectArea: "ప్రాంతాన్ని ఎంచుకోండి...",
    currentStatus: "ప్రస్తుత స్థితి",
    clean: "శుభ్రం",
    needsCleaning: "శుభ్రత అవసరం",
    overflowing: "పొంగిపొర్లుతోంది",
    comments: "వ్యాఖ్యలు",
    anyNotes: "ఏదైనా గమనికలు...",
    photoRequired: "ఫోటో అవసరం — అప్‌లోడ్ చేయడానికి క్లిక్ చేయండి",
    mySubmissions: "నా సమర్పణలు",
    noPhotosYet: "ఇంకా ఫోటోలు లేవు",
    pending: "పెండింగ్",
    reviewed: "సమీక్షించబడింది",
    cleaned: "శుభ్రం చేయబడింది",
    weeklyVendorRankings: "వారపు విక్రేత ర్యాంకింగ్‌లు",
    pointsEarned: "ఈ వారం సంపాదించిన పాయింట్లు",
    cleanReports: "శుభ్రమైన నివేదికలు",
    municipalityDashboard: "మున్సిపాలిటీ డాష్‌బోర్డ్",
    monitorManage: "మార్కెట్ పరిశుభ్రతను పర్యవేక్షించండి మరియు నిర్వహించండి",
    awaitingReview: "సమీక్ష కోసం వేచి ఉంది",
    underAction: "చర్యలో ఉంది",
    completed: "పూర్తయింది",
    totalVendors: "మొత్తం విక్రేతలు",
    registered: "నమోదు",
    photoReview: "ఫోటో సమీక్ష",
    vendorRankings: "విక్రేత ర్యాంకింగ్‌లు",
    marketPhotos: "మార్కెట్ ఫోటోలు",
    reviewManagePhotos: "సమర్పించిన ఫోటోలను సమీక్షించండి మరియు నిర్వహించండి",
    filterByStatus: "స్థితి ద్వారా ఫిల్టర్ చేయండి",
    allPhotos: "అన్ని ఫోటోలు",
    filterByArea: "ప్రాంతం ద్వారా ఫిల్టర్ చేయండి",
    allAreas: "అన్ని ప్రాంతాలు",
    vendor: "విక్రేత",
    uploaded: "అప్‌లోడ్ చేయబడింది",
    score: "స్కోర్",
    markAsReviewed: "సమీక్షించినట్లు గుర్తించండి",
    markAsCleaned: "శుభ్రం చేసినట్లు గుర్తించండి",
    noPhotosSubmitted: "ఇంకా ఫోటోలు సమర్పించబడలేదు.",
    vendorsRankedByPoints: "ఈ వారం సంపాదించిన మొత్తం పాయింట్ల ద్వారా విక్రేతలు ర్యాంక్ చేయబడ్డారు",
    photos: "ఫోటోలు",
    points: "పాయింట్లు",
    vegetablesSection: "కూరగాయల విభాగం",
    fruitsSection: "పండ్ల విభాగం",
    flowerMarket: "పువ్వుల మార్కెట్",
    fishMarket: "చేపల మార్కెట్",
    meatMarket: "మాంసం మార్కెట్",
    pathway: "మార్గం",
    dustbinZone: "డస్ట్‌బిన్ జోన్",
    other: "ఇతర",
    stallPlaceholder: "ఉదా., A-12",
    uploadSuccess: "ధన్యవాదాలు — మీ నివేదిక రికార్డ్ చేయబడింది. మున్సిపల్ సమీక్ష పెండింగ్‌లో ఉంది.",
    uploadError: "ఫోటో అప్‌లోడ్ చేయడంలో లోపం",
    pleaseUploadImage: "దయచేసి ఇమేజ్ ఫైల్ అప్‌లోడ్ చేయండి",
    fileSizeLimit: "ఫైల్ సైజు 5MB కంటే తక్కువ ఉండాలి",
    noAreaSpecified: "ప్రాంతం పేర్కొనబడలేదు",
    pts: "పాయింట్లు",
    pt: "పాయింట్",
    unknownMarket: "తెలియని మార్కెట్",
    unknownVendor: "తెలియదు",
    failedToUpdateStatus: "స్థితిని అప్‌డేట్ చేయడం విఫలమైంది",
    statusUpdatedTo: "స్థితి అప్‌డేట్ చేయబడింది",
    photoMarkedCleaned: "ఫోటో శుభ్రంగా గుర్తించబడింది — విక్రేతకు +1 పాయింట్",
    photoMarkedReviewed: "ఫోటో సమీక్షించబడినట్లు గుర్తించబడింది — పాయింట్లు లేవు",
    failedToMarkPhoto: "ఫోటోను గుర్తించడం విఫలమైంది",
    failedToLoadRankings: "ర్యాంకింగ్‌లను లోడ్ చేయడం విఫలమైంది",
    failedToUpdateRankings: "ర్యాంకింగ్‌లను అప్‌డేట్ చేయడం విఫలమైంది",
    loading: "లోడ్ అవుతోంది...",
    loadMore: "మరింత లోడ్ చేయండి",
    noInternet: "ఇంటర్నెట్ కనెక్షన్ లేదు",
    uploadRetrying: "అప్‌లోడ్ మళ్ళీ ప్రయత్నిస్తోంది...",
    uploadQueued: "అప్‌లోడ్ క్యూలో ఉంది",
    uploadFailed: "అప్‌లోడ్ విఫలమైంది",
    retryUpload: "మళ్ళీ ప్రయత్నించు",
    retryAll: "అన్నీ మళ్ళీ ప్రయత్నించు",
    uploadingPhoto: "ఫోటో అప్‌లోడ్ అవుతోంది...",
    queuedUploads: "అప్‌లోడ్‌లు క్యూలో ఉన్నాయి",
    failedUploads: "అప్‌లోడ్‌లు విఫలమయ్యాయి",
    dismiss: "తొలగించు",
    offlineMode: "ఆఫ్‌లైన్ మోడ్",
    willRetryWhenOnline: "ఆన్‌లైన్‌లో ఉన్నప్పుడు మళ్ళీ ప్రయత్నిస్తుంది",
    serverUnavailable: "సర్వర్ అందుబాటులో లేదు",
    retryingAutomatically: "ఆటోమేటిక్‌గా మళ్ళీ ప్రయత్నిస్తోంది...",
    retryCount: "మళ్ళీ ప్రయత్నాలు",
    myReviews: "నా సమీక్షలు",
    noPendingPhotos: "సమీక్షించడానికి పెండింగ్ ఫోటోలు లేవు",
    noReviewsYet: "మీరు ఇంకా ఎలాంటి ఫోటోలను సమీక్షించలేదు",
  },
  bn: {
    cleanMarketInitiative: "পরিষ্কার বাজার উদ্যোগ",
    appName: "UrbanEye AI",
    tagline: "পরিষ্কার, স্বাস্থ্যকর পাবলিক মার্কেটের জন্য বিক্রেতাদের অফিসারদের সাথে সংযুক্ত করা পৌর বর্জ্য ব্যবস্থাপনা সিস্টেম",
    getStarted: "শুরু করুন",
    installApp: "অ্যাপ ইনস্টল করুন",
    howItWorks: "এটি কীভাবে কাজ করে",
    howItWorksDesc: "বাজারের পরিচ্ছন্নতা বজায় রাখতে একটি সহজ তিন-ধাপের প্রক্রিয়া",
    vendorsUpload: "বিক্রেতারা আপলোড করুন",
    vendorsUploadDesc: "বাজারের বিক্রেতারা তাদের এলাকার ছবি তোলেন এবং বর্জ্য রিপোর্ট করতে বা পরিচ্ছন্নতা প্রদর্শন করতে ছবি আপলোড করেন",
    officersReview: "অফিসাররা পর্যালোচনা করুন",
    officersReviewDesc: "পৌরসভার অফিসাররা জমাগুলি পর্যালোচনা করেন এবং যে এলাকাগুলিতে মনোযোগ প্রয়োজন সেখানে পরিষ্কার কর্মী পাঠান",
    vendorsGetRanked: "বিক্রেতারা র‌্যাঙ্ক পান",
    vendorsGetRankedDesc: "সক্রিয় বিক্রেতারা সাপ্তাহিক র‌্যাঙ্ক পান, সবচেয়ে সক্রিয় বিক্রেতাকে \"সপ্তাহের পরিষ্কার বিক্রেতা\" মুকুট দেওয়া হয়",
    readyToJoin: "যোগ দিতে প্রস্তুত?",
    readyToJoinDesc: "আপনি বাজারের বিক্রেতা হোন বা পৌরসভার অফিসার, আজই মার্কেটসেন্সে যোগ দিন এবং পরিষ্কার, স্বাস্থ্যকর পাবলিক স্থানে অবদান রাখুন।",
    signUpNow: "এখনই সাইন আপ করুন",
    footer: "© 2024 মার্কেটসেন্স। একসাথে পরিষ্কার সম্প্রদায় গড়ে তোলা।",
    selectLanguage: "ভাষা নির্বাচন করুন",
    login: "লগইন",
    signUp: "সাইন আপ",
    welcomeBack: "স্বাগত ফিরে",
    enterCredentials: "চালিয়ে যেতে আপনার তথ্য দিন",
    createAccount: "অ্যাকাউন্ট তৈরি করুন",
    joinInitiative: "মার্কেটসেন্স উদ্যোগে যোগ দিন",
    email: "ইমেইল",
    password: "পাসওয়ার্ড",
    fullName: "পুরো নাম",
    iAmA: "আমি একজন",
    marketVendor: "বাজার বিক্রেতা",
    municipalityOfficer: "পৌরসভা অফিসার",
    marketName: "বাজারের নাম",
    loggingIn: "লগইন হচ্ছে...",
    creatingAccount: "অ্যাকাউন্ট তৈরি হচ্ছে...",
    wasteManagementSystem: "পাবলিক মার্কেটের জন্য বর্জ্য ব্যবস্থাপনা সিস্টেম",
    logout: "লগআউট",
    photosSubmitted: "জমা দেওয়া ছবি",
    pointsThisWeek: "এই সপ্তাহে পয়েন্ট",
    currentStreak: "বর্তমান স্ট্রিক",
    weeklyRank: "সাপ্তাহিক র‌্যাঙ্ক",
    vendorDashboard: "বিক্রেতা ড্যাশবোর্ড",
    submitReport: "রিপোর্ট জমা দিন",
    rankings: "র‌্যাঙ্কিং",
    reportStallStatus: "স্টলের অবস্থা রিপোর্ট করুন",
    reportStallStatusDesc: "অবস্থা নির্বাচন করুন এবং ছবি আপলোড করুন — পৌরসভা অফিসাররা পর্যালোচনা করবেন।",
    stallNumber: "স্টল নম্বর",
    marketArea: "বাজার এলাকা",
    selectArea: "এলাকা নির্বাচন করুন...",
    currentStatus: "বর্তমান অবস্থা",
    clean: "পরিষ্কার",
    needsCleaning: "পরিষ্কার প্রয়োজন",
    overflowing: "উপচে পড়ছে",
    comments: "মন্তব্য",
    anyNotes: "কোনো নোট...",
    photoRequired: "ছবি প্রয়োজন — আপলোড করতে ক্লিক করুন",
    mySubmissions: "আমার জমা",
    noPhotosYet: "এখনো কোনো ছবি নেই",
    pending: "মুলতুবি",
    reviewed: "পর্যালোচিত",
    cleaned: "পরিষ্কার করা হয়েছে",
    weeklyVendorRankings: "সাপ্তাহিক বিক্রেতা র‌্যাঙ্কিং",
    pointsEarned: "এই সপ্তাহে অর্জিত পয়েন্ট",
    cleanReports: "পরিষ্কার রিপোর্ট",
    municipalityDashboard: "পৌরসভা ড্যাশবোর্ড",
    monitorManage: "বাজারের পরিচ্ছন্নতা পর্যবেক্ষণ ও পরিচালনা করুন",
    awaitingReview: "পর্যালোচনার অপেক্ষায়",
    underAction: "কার্যক্রমে",
    completed: "সম্পন্ন",
    totalVendors: "মোট বিক্রেতা",
    registered: "নিবন্ধিত",
    photoReview: "ছবি পর্যালোচনা",
    vendorRankings: "বিক্রেতা র‌্যাঙ্কিং",
    marketPhotos: "বাজারের ছবি",
    reviewManagePhotos: "জমা দেওয়া ছবি পর্যালোচনা ও পরিচালনা করুন",
    filterByStatus: "অবস্থা দ্বারা ফিল্টার",
    allPhotos: "সব ছবি",
    filterByArea: "এলাকা দ্বারা ফিল্টার",
    allAreas: "সব এলাকা",
    vendor: "বিক্রেতা",
    uploaded: "আপলোড করা হয়েছে",
    score: "স্কোর",
    markAsReviewed: "পর্যালোচিত হিসেবে চিহ্নিত করুন",
    markAsCleaned: "পরিষ্কার হিসেবে চিহ্নিত করুন",
    noPhotosSubmitted: "এখনো কোনো ছবি জমা দেওয়া হয়নি।",
    vendorsRankedByPoints: "এই সপ্তাহে অর্জিত মোট পয়েন্ট দ্বারা বিক্রেতারা র‌্যাঙ্ক করা হয়েছে",
    photos: "ছবি",
    points: "পয়েন্ট",
    vegetablesSection: "সবজি বিভাগ",
    fruitsSection: "ফল বিভাগ",
    flowerMarket: "ফুলের বাজার",
    fishMarket: "মাছের বাজার",
    meatMarket: "মাংসের বাজার",
    pathway: "পথ",
    dustbinZone: "ডাস্টবিন জোন",
    other: "অন্যান্য",
    stallPlaceholder: "যেমন, A-12",
    uploadSuccess: "ধন্যবাদ — আপনার রিপোর্ট রেকর্ড করা হয়েছে। পৌরসভা পর্যালোচনা মুলতুবি।",
    uploadError: "ছবি আপলোড করতে ত্রুটি",
    pleaseUploadImage: "অনুগ্রহ করে একটি ছবি ফাইল আপলোড করুন",
    fileSizeLimit: "ফাইলের আকার 5MB এর কম হতে হবে",
    noAreaSpecified: "এলাকা নির্দিষ্ট নয়",
    pts: "পয়েন্ট",
    pt: "পয়েন্ট",
    unknownMarket: "অজানা বাজার",
    unknownVendor: "অজানা",
    failedToUpdateStatus: "স্থিতি আপডেট করতে ব্যর্থ",
    statusUpdatedTo: "স্থিতি আপডেট হয়েছে",
    photoMarkedCleaned: "ছবি পরিষ্কার হিসেবে চিহ্নিত — বিক্রেতাকে +1 পয়েন্ট দেওয়া হয়েছে",
    photoMarkedReviewed: "ছবি পর্যালোচনা করা হয়েছে হিসেবে চিহ্নিত — কোনো পয়েন্ট নেই",
    failedToMarkPhoto: "ছবি চিহ্নিত করতে ব্যর্থ",
    failedToLoadRankings: "র‌্যাঙ্কিং লোড করতে ব্যর্থ",
    failedToUpdateRankings: "র‌্যাঙ্কিং আপডেট করতে ব্যর্থ",
    loading: "লোড হচ্ছে...",
    loadMore: "আরও লোড করুন",
    noInternet: "ইন্টারনেট সংযোগ নেই",
    uploadRetrying: "আপলোড পুনরায় চেষ্টা হচ্ছে...",
    uploadQueued: "আপলোড সারিতে আছে",
    uploadFailed: "আপলোড ব্যর্থ",
    retryUpload: "পুনরায় চেষ্টা",
    retryAll: "সব পুনরায় চেষ্টা",
    uploadingPhoto: "ছবি আপলোড হচ্ছে...",
    queuedUploads: "আপলোড সারিতে আছে",
    failedUploads: "আপলোড ব্যর্থ হয়েছে",
    dismiss: "বাতিল",
    offlineMode: "অফলাইন মোড",
    willRetryWhenOnline: "অনলাইনে গেলে পুনরায় চেষ্টা হবে",
    serverUnavailable: "সার্ভার অনুপলব্ধ",
    retryingAutomatically: "স্বয়ংক্রিয়ভাবে পুনরায় চেষ্টা হচ্ছে...",
    retryCount: "পুনরায় চেষ্টা",
    myReviews: "আমার পর্যালোচনা",
    noPendingPhotos: "পর্যালোচনার জন্য কোনো মুলতুবি ছবি নেই",
    noReviewsYet: "আপনি এখনও কোনো ছবি পর্যালোচনা করেননি",
  },
  mr: {
    cleanMarketInitiative: "स्वच्छ बाजार उपक्रम",
    appName: "UrbanEye AI",
    tagline: "स्वच्छ, निरोगी सार्वजनिक बाजारांसाठी विक्रेत्यांना अधिकाऱ्यांशी जोडणारी नगरपालिका कचरा व्यवस्थापन प्रणाली",
    getStarted: "सुरू करा",
    installApp: "अॅप स्थापित करा",
    howItWorks: "हे कसे कार्य करते",
    howItWorksDesc: "बाजाराची स्वच्छता राखण्याची एक सोपी तीन-चरण प्रक्रिया",
    vendorsUpload: "विक्रेते अपलोड करा",
    vendorsUploadDesc: "बाजारातील विक्रेते त्यांच्या भागांचे फोटो काढतात आणि कचरा नोंदवण्यासाठी किंवा स्वच्छता दाखवण्यासाठी प्रतिमा अपलोड करतात",
    officersReview: "अधिकारी पुनरावलोकन करा",
    officersReviewDesc: "नगरपालिका अधिकारी सबमिशनचे पुनरावलोकन करतात आणि लक्ष देणे आवश्यक असलेल्या भागांमध्ये स्वच्छता कर्मचारी पाठवतात",
    vendorsGetRanked: "विक्रेत्यांना रँक मिळतो",
    vendorsGetRankedDesc: "सक्रिय विक्रेत्यांना साप्ताहिक रँक मिळतो, सर्वात सक्रिय विक्रेत्याला \"आठवड्याचा स्वच्छ विक्रेता\" हा मुकुट मिळतो",
    readyToJoin: "सामील होण्यास तयार?",
    readyToJoinDesc: "तुम्ही बाजारातील विक्रेते असाल किंवा नगरपालिका अधिकारी, आजच मार्केटसेन्समध्ये सामील व्हा आणि स्वच्छ, निरोगी सार्वजनिक जागांमध्ये योगदान द्या.",
    signUpNow: "आता साइन अप करा",
    footer: "© 2024 मार्केटसेन्स। एकत्र स्वच्छ समुदाय बांधणे.",
    selectLanguage: "भाषा निवडा",
    login: "लॉगिन",
    signUp: "साइन अप",
    welcomeBack: "पुन्हा स्वागत",
    enterCredentials: "सुरू ठेवण्यासाठी आपला तपशील प्रविष्ट करा",
    createAccount: "खाते तयार करा",
    joinInitiative: "मार्केटसेन्स उपक्रमात सामील व्हा",
    email: "ईमेल",
    password: "पासवर्ड",
    fullName: "पूर्ण नाव",
    iAmA: "मी एक",
    marketVendor: "बाजार विक्रेता",
    municipalityOfficer: "नगरपालिका अधिकारी",
    marketName: "बाजाराचे नाव",
    loggingIn: "लॉगिन होत आहे...",
    creatingAccount: "खाते तयार होत आहे...",
    wasteManagementSystem: "सार्वजनिक बाजारांसाठी कचरा व्यवस्थापन प्रणाली",
    logout: "लॉगआउट",
    photosSubmitted: "सबमिट केलेले फोटो",
    pointsThisWeek: "या आठवड्यात गुण",
    currentStreak: "सध्याची स्ट्रीक",
    weeklyRank: "साप्ताहिक रँक",
    vendorDashboard: "विक्रेता डॅशबोर्ड",
    submitReport: "अहवाल सबमिट करा",
    rankings: "रँकिंग",
    reportStallStatus: "स्टॉल स्थिती नोंदवा",
    reportStallStatusDesc: "स्थिती निवडा आणि फोटो अपलोड करा — नगरपालिका अधिकारी पुनरावलोकन करतील.",
    stallNumber: "स्टॉल क्रमांक",
    marketArea: "बाजार क्षेत्र",
    selectArea: "क्षेत्र निवडा...",
    currentStatus: "सध्याची स्थिती",
    clean: "स्वच्छ",
    needsCleaning: "स्वच्छता आवश्यक",
    overflowing: "ओव्हरफ्लो",
    comments: "टिप्पण्या",
    anyNotes: "कोणत्याही नोट्स...",
    photoRequired: "फोटो आवश्यक — अपलोड करण्यासाठी क्लिक करा",
    mySubmissions: "माझी सबमिशन",
    noPhotosYet: "अजून फोटो नाहीत",
    pending: "प्रलंबित",
    reviewed: "पुनरावलोकन केले",
    cleaned: "स्वच्छ केले",
    weeklyVendorRankings: "साप्ताहिक विक्रेता रँकिंग",
    pointsEarned: "या आठवड्यात मिळवलेले गुण",
    cleanReports: "स्वच्छ अहवाल",
    municipalityDashboard: "नगरपालिका डॅशबोर्ड",
    monitorManage: "बाजाराची स्वच्छता निरीक्षण आणि व्यवस्थापित करा",
    awaitingReview: "पुनरावलोकनाची वाट पाहत आहे",
    underAction: "कारवाईत",
    completed: "पूर्ण",
    totalVendors: "एकूण विक्रेते",
    registered: "नोंदणीकृत",
    photoReview: "फोटो पुनरावलोकन",
    vendorRankings: "विक्रेता रँकिंग",
    marketPhotos: "बाजार फोटो",
    reviewManagePhotos: "सबमिट केलेले फोटो पुनरावलोकन आणि व्यवस्थापित करा",
    filterByStatus: "स्थितीनुसार फिल्टर करा",
    allPhotos: "सर्व फोटो",
    filterByArea: "क्षेत्रानुसार फिल्टर करा",
    allAreas: "सर्व क्षेत्रे",
    vendor: "विक्रेता",
    uploaded: "अपलोड केले",
    score: "स्कोर",
    markAsReviewed: "पुनरावलोकन केले म्हणून चिन्हांकित करा",
    markAsCleaned: "स्वच्छ केले म्हणून चिन्हांकित करा",
    noPhotosSubmitted: "अजून कोणतेही फोटो सबमिट केलेले नाहीत.",
    vendorsRankedByPoints: "या आठवड्यात मिळवलेल्या एकूण गुणांनुसार विक्रेत्यांना रँक केले आहे",
    photos: "फोटो",
    points: "गुण",
    vegetablesSection: "भाजीपाला विभाग",
    fruitsSection: "फळ विभाग",
    flowerMarket: "फूल बाजार",
    fishMarket: "मासे बाजार",
    meatMarket: "मांस बाजार",
    pathway: "मार्ग",
    dustbinZone: "कचरापेटी झोन",
    other: "इतर",
    stallPlaceholder: "उदा., A-12",
    uploadSuccess: "धन्यवाद — तुमचा अहवाल नोंदवला गेला आहे. नगरपालिका पुनरावलोकन प्रलंबित.",
    uploadError: "फोटो अपलोड करण्यात त्रुटी",
    pleaseUploadImage: "कृपया एक प्रतिमा फाइल अपलोड करा",
    fileSizeLimit: "फाइल आकार 5MB पेक्षा कमी असणे आवश्यक आहे",
    noAreaSpecified: "क्षेत्र निर्दिष्ट नाही",
    pts: "गुण",
    pt: "गुण",
    unknownMarket: "अज्ञात बाजार",
    unknownVendor: "अज्ञात",
    failedToUpdateStatus: "स्थिती अपडेट करण्यात अयशस्वी",
    statusUpdatedTo: "स्थिती अपडेट झाली",
    photoMarkedCleaned: "फोटो स्वच्छ म्हणून चिन्हांकित — विक्रेत्याला +1 गुण मिळाला",
    photoMarkedReviewed: "फोटो पुनरावलोकन केले म्हणून चिन्हांकित — कोणतेही गुण नाहीत",
    failedToMarkPhoto: "फोटो चिन्हांकित करण्यात अयशस्वी",
    failedToLoadRankings: "रँकिंग लोड करण्यात अयशस्वी",
    failedToUpdateRankings: "रँकिंग अपडेट करण्यात अयशस्वी",
    loading: "लोड होत आहे...",
    loadMore: "आणखी लोड करा",
    noInternet: "इंटरनेट कनेक्शन नाही",
    uploadRetrying: "अपलोड पुन्हा प्रयत्न होत आहे...",
    uploadQueued: "अपलोड रांगेत आहे",
    uploadFailed: "अपलोड अयशस्वी",
    retryUpload: "पुन्हा प्रयत्न करा",
    retryAll: "सर्व पुन्हा प्रयत्न करा",
    uploadingPhoto: "फोटो अपलोड होत आहे...",
    queuedUploads: "अपलोड रांगेत आहेत",
    failedUploads: "अपलोड अयशस्वी झाले",
    dismiss: "नाकारा",
    offlineMode: "ऑफलाइन मोड",
    willRetryWhenOnline: "ऑनलाइन झाल्यावर पुन्हा प्रयत्न होईल",
    serverUnavailable: "सर्व्हर उपलब्ध नाही",
    retryingAutomatically: "आपोआप पुन्हा प्रयत्न होत आहे...",
    retryCount: "पुन्हा प्रयत्न",
    myReviews: "माझी पुनरावलोकने",
    noPendingPhotos: "पुनरावलोकनासाठी कोणतेही प्रलंबित फोटो नाहीत",
    noReviewsYet: "तुम्ही अद्याप कोणतेही फोटो पुनरावलोकन केले नाहीत",
  },
  gu: {
    cleanMarketInitiative: "સ્વચ્છ બજાર પહેલ",
    appName: "UrbanEye AI",
    tagline: "સ્વચ્છ, સ્વસ્થ જાહેર બજારો માટે વિક્રેતાઓને અધિકારીઓ સાથે જોડતી મ્યુનિસિપલ કચરો વ્યવસ્થાપન સિસ્ટમ",
    getStarted: "શરૂ કરો",
    installApp: "એપ ઇન્સ્ટોલ કરો",
    howItWorks: "આ કેવી રીતે કામ કરે છે",
    howItWorksDesc: "બજારની સ્વચ્છતા જાળવવાની એક સરળ ત્રણ-પગલાંની પ્રક્રિયા",
    vendorsUpload: "વિક્રેતાઓ અપલોડ કરો",
    vendorsUploadDesc: "બજારના વિક્રેતાઓ તેમના વિસ્તારોના ફોટો લે છે અને કચરાની જાણ કરવા અથવા સ્વચ્છતા દર્શાવવા છબીઓ અપલોડ કરે છે",
    officersReview: "અધિકારીઓ સમીક્ષા કરો",
    officersReviewDesc: "મ્યુનિસિપાલિટી અધિકારીઓ સબમિશનની સમીક્ષા કરે છે અને ધ્યાન આપવાની જરૂર હોય તેવા વિસ્તારોમાં સફાઈ કર્મચારીઓ મોકલે છે",
    vendorsGetRanked: "વિક્રેતાઓને રેન્ક મળે છે",
    vendorsGetRankedDesc: "સક્રિય વિક્રેતાઓને સાપ્તાહિક રેન્ક મળે છે, સૌથી વધુ સક્રિય વિક્રેતાને \"અઠવાડિયાના સ્વચ્છ વિક્રેતા\" નો તાજ મળે છે",
    readyToJoin: "જોડાવા તૈયાર?",
    readyToJoinDesc: "તમે બજારના વિક્રેતા હો કે મ્યુનિસિપાલિટી અધિકારી, આજે જ માર્કેટસેન્સમાં જોડાઓ અને સ્વચ્છ, સ્વસ્થ જાહેર જગ્યાઓમાં યોગદાન આપો.",
    signUpNow: "હમણાં સાઇન અપ કરો",
    footer: "© 2024 માર્કેટસેન્સ। સાથે મળીને સ્વચ્છ સમુદાયો બનાવવું.",
    selectLanguage: "ભાષા પસંદ કરો",
    login: "લોગિન",
    signUp: "સાઇન અપ",
    welcomeBack: "પાછા સ્વાગત છે",
    enterCredentials: "ચાલુ રાખવા માટે તમારી વિગતો દાખલ કરો",
    createAccount: "એકાઉન્ટ બનાવો",
    joinInitiative: "માર્કેટસેન્સ પહેલમાં જોડાઓ",
    email: "ઇમેઇલ",
    password: "પાસવર્ડ",
    fullName: "પૂરું નામ",
    iAmA: "હું એક",
    marketVendor: "બજાર વિક્રેતા",
    municipalityOfficer: "મ્યુનિસિપાલિટી અધિકારી",
    marketName: "બજારનું નામ",
    loggingIn: "લોગિન થઈ રહ્યું છે...",
    creatingAccount: "એકાઉન્ટ બની રહ્યું છે...",
    wasteManagementSystem: "જાહેર બજારો માટે કચરો વ્યવસ્થાપન સિસ્ટમ",
    logout: "લોગઆઉટ",
    photosSubmitted: "સબમિટ કરેલા ફોટો",
    pointsThisWeek: "આ અઠવાડિયે પોઇન્ટ્સ",
    currentStreak: "વર્તમાન સ્ટ્રીક",
    weeklyRank: "સાપ્તાહિક રેન્ક",
    vendorDashboard: "વિક્રેતા ડેશબોર્ડ",
    submitReport: "રિપોર્ટ સબમિટ કરો",
    rankings: "રેન્કિંગ",
    reportStallStatus: "સ્ટોલની સ્થિતિ જણાવો",
    reportStallStatusDesc: "સ્થિતિ પસંદ કરો અને ફોટો અપલોડ કરો — મ્યુનિસિપલ અધિકારીઓ સમીક્ષા કરશે.",
    stallNumber: "સ્ટોલ નંબર",
    marketArea: "બજાર વિસ્તાર",
    selectArea: "વિસ્તાર પસંદ કરો...",
    currentStatus: "વર્તમાન સ્થિતિ",
    clean: "સ્વચ્છ",
    needsCleaning: "સફાઈ જરૂરી",
    overflowing: "ઓવરફ્લો",
    comments: "ટિપ્પણીઓ",
    anyNotes: "કોઈ નોંધો...",
    photoRequired: "ફોટો જરૂરી — અપલોડ કરવા ક્લિક કરો",
    mySubmissions: "મારા સબમિશન",
    noPhotosYet: "હજુ ફોટો નથી",
    pending: "બાકી",
    reviewed: "સમીક્ષા થઈ",
    cleaned: "સાફ થયું",
    weeklyVendorRankings: "સાપ્તાહિક વિક્રેતા રેન્કિંગ",
    pointsEarned: "આ અઠવાડિયે મેળવેલા પોઇન્ટ્સ",
    cleanReports: "સ્વચ્છ રિપોર્ટ્સ",
    municipalityDashboard: "મ્યુનિસિપાલિટી ડેશબોર્ડ",
    monitorManage: "બજારની સ્વચ્છતા મોનિટર અને મેનેજ કરો",
    awaitingReview: "સમીક્ષાની રાહ જોઈ રહ્યા છીએ",
    underAction: "કાર્યવાહીમાં",
    completed: "પૂર્ણ",
    totalVendors: "કુલ વિક્રેતાઓ",
    registered: "નોંધાયેલ",
    photoReview: "ફોટો સમીક્ષા",
    vendorRankings: "વિક્રેતા રેન્કિંગ",
    marketPhotos: "બજાર ફોટો",
    reviewManagePhotos: "સબમિટ કરેલા ફોટોની સમીક્ષા અને મેનેજ કરો",
    filterByStatus: "સ્થિતિ દ્વારા ફિલ્ટર કરો",
    allPhotos: "બધા ફોટો",
    filterByArea: "વિસ્તાર દ્વારા ફિલ્ટર કરો",
    allAreas: "બધા વિસ્તારો",
    vendor: "વિક્રેતા",
    uploaded: "અપલોડ થયું",
    score: "સ્કોર",
    markAsReviewed: "સમીક્ષા થયેલ તરીકે ચિહ્નિત કરો",
    markAsCleaned: "સાફ થયેલ તરીકે ચિહ્નિત કરો",
    noPhotosSubmitted: "હજુ કોઈ ફોટો સબમિટ થયા નથી.",
    vendorsRankedByPoints: "આ અઠવાડિયે મેળવેલા કુલ પોઇન્ટ્સ દ્વારા વિક્રેતાઓ રેન્ક થયા છે",
    photos: "ફોટો",
    points: "પોઇન્ટ્સ",
    vegetablesSection: "શાકભાજી વિભાગ",
    fruitsSection: "ફળ વિભાગ",
    flowerMarket: "ફૂલ બજાર",
    fishMarket: "માછલી બજાર",
    meatMarket: "માંસ બજાર",
    pathway: "રસ્તો",
    dustbinZone: "ડસ્ટબિન ઝોન",
    other: "અન્ય",
    stallPlaceholder: "ઉદા., A-12",
    uploadSuccess: "આભાર — તમારો રિપોર્ટ નોંધાયો છે. મ્યુનિસિપાલિટી સમીક્ષા બાકી.",
    uploadError: "ફોટો અપલોડ કરવામાં ભૂલ",
    pleaseUploadImage: "કૃપા કરીને છબી ફાઇલ અપલોડ કરો",
    fileSizeLimit: "ફાઇલ સાઇઝ 5MB કરતાં ઓછી હોવી જોઈએ",
    noAreaSpecified: "વિસ્તાર નિર્દિષ્ટ નથી",
    pts: "પોઇન્ટ્સ",
    pt: "પોઇન્ટ",
    unknownMarket: "અજાણ્યું બજાર",
    unknownVendor: "અજાણ્યું",
    failedToUpdateStatus: "સ્થિતિ અપડેટ કરવામાં નિષ્ફળ",
    statusUpdatedTo: "સ્થિતિ અપડેટ થઈ",
    photoMarkedCleaned: "ફોટો સાફ તરીકે ચિહ્નિત — વિક્રેતાને +1 પોઇન્ટ",
    photoMarkedReviewed: "ફોટો સમીક્ષા થયેલ તરીકે ચિહ્નિત — કોઈ પોઇન્ટ્સ નથી",
    failedToMarkPhoto: "ફોટો ચિહ્નિત કરવામાં નિષ્ફળ",
    failedToLoadRankings: "રેન્કિંગ લોડ કરવામાં નિષ્ફળ",
    failedToUpdateRankings: "રેન્કિંગ અપડેટ કરવામાં નિષ્ફળ",
    loading: "લોડ થઈ રહ્યું છે...",
    loadMore: "વધુ લોડ કરો",
    noInternet: "ઇન્ટરનેટ કનેક્શન નથી",
    uploadRetrying: "અપલોડ ફરીથી પ્રયાસ થઈ રહ્યો છે...",
    uploadQueued: "અપલોડ કતારમાં છે",
    uploadFailed: "અપલોડ નિષ્ફળ",
    retryUpload: "ફરી પ્રયાસ કરો",
    retryAll: "બધા ફરી પ્રયાસ કરો",
    uploadingPhoto: "ફોટો અપલોડ થઈ રહ્યો છે...",
    queuedUploads: "અપલોડ કતારમાં છે",
    failedUploads: "અપલોડ નિષ્ફળ થયા",
    dismiss: "રદ કરો",
    offlineMode: "ઑફલાઇન મોડ",
    willRetryWhenOnline: "ઓનલાઇન હશો ત્યારે ફરી પ્રયાસ થશે",
    serverUnavailable: "સર્વર ઉપલબ્ધ નથી",
    retryingAutomatically: "આપોઆપ ફરી પ્રયાસ થઈ રહ્યો છે...",
    retryCount: "ફરી પ્રયાસ",
    myReviews: "મારી સમીક્ષાઓ",
    noPendingPhotos: "સમીક્ષા માટે કોઈ બાકી ફોટા નથી",
    noReviewsYet: "તમે હજુ સુધી કોઈ ફોટાની સમીક્ષા કરી નથી",
  },
  kn: {
    cleanMarketInitiative: "ಸ್ವಚ್ಛ ಮಾರುಕಟ್ಟೆ ಉಪಕ್ರಮ",
    appName: "UrbanEye AI",
    tagline: "ಸ್ವಚ್ಛ, ಆರೋಗ್ಯಕರ ಸಾರ್ವಜನಿಕ ಮಾರುಕಟ್ಟೆಗಳಿಗಾಗಿ ಮಾರಾಟಗಾರರನ್ನು ಅಧಿಕಾರಿಗಳೊಂದಿಗೆ ಸಂಪರ್ಕಿಸುವ ಮುನ್ಸಿಪಲ್ ತ್ಯಾಜ್ಯ ನಿರ್ವಹಣಾ ವ್ಯವಸ್ಥೆ",
    getStarted: "ಪ್ರಾರಂಭಿಸಿ",
    installApp: "ಅಪ್ಲಿಕೇಶನ್ ಸ್ಥಾಪಿಸಿ",
    howItWorks: "ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ",
    howItWorksDesc: "ಮಾರುಕಟ್ಟೆ ಸ್ವಚ್ಛತೆಯನ್ನು ಕಾಪಾಡಿಕೊಳ್ಳಲು ಸರಳ ಮೂರು-ಹಂತದ ಪ್ರಕ್ರಿಯೆ",
    vendorsUpload: "ಮಾರಾಟಗಾರರು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    vendorsUploadDesc: "ಮಾರುಕಟ್ಟೆ ಮಾರಾಟಗಾರರು ತಮ್ಮ ಪ್ರದೇಶಗಳ ಫೋಟೋ ತೆಗೆದು ತ್ಯಾಜ್ಯವನ್ನು ವರದಿ ಮಾಡಲು ಅಥವಾ ಸ್ವಚ್ಛತೆಯನ್ನು ಪ್ರದರ್ಶಿಸಲು ಚಿತ್ರಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡುತ್ತಾರೆ",
    officersReview: "ಅಧಿಕಾರಿಗಳು ಪರಿಶೀಲಿಸಿ",
    officersReviewDesc: "ಮುನ್ಸಿಪಾಲಿಟಿ ಅಧಿಕಾರಿಗಳು ಸಲ್ಲಿಕೆಗಳನ್ನು ಪರಿಶೀಲಿಸುತ್ತಾರೆ ಮತ್ತು ಗಮನ ಅಗತ್ಯವಿರುವ ಪ್ರದೇಶಗಳಿಗೆ ಸ್ವಚ್ಛತಾ ಸಿಬ್ಬಂದಿಯನ್ನು ಕಳುಹಿಸುತ್ತಾರೆ",
    vendorsGetRanked: "ಮಾರಾಟಗಾರರು ರ‌್ಯಾಂಕ್ ಪಡೆಯುತ್ತಾರೆ",
    vendorsGetRankedDesc: "ಸಕ್ರಿಯ ಮಾರಾಟಗಾರರು ವಾರಕ್ಕೊಮ್ಮೆ ರ‌್ಯಾಂಕ್ ಪಡೆಯುತ್ತಾರೆ, ಅತ್ಯಂತ ತೊಡಗಿಸಿಕೊಂಡ ಮಾರಾಟಗಾರರಿಗೆ \"ವಾರದ ಸ್ವಚ್ಛ ಮಾರಾಟಗಾರ\" ಎಂಬ ಕಿರೀಟ ನೀಡಲಾಗುತ್ತದೆ",
    readyToJoin: "ಸೇರಲು ಸಿದ್ಧರಿದ್ದೀರಾ?",
    readyToJoinDesc: "ನೀವು ಮಾರುಕಟ್ಟೆ ಮಾರಾಟಗಾರರಾಗಿರಲಿ ಅಥವಾ ಮುನ್ಸಿಪಾಲಿಟಿ ಅಧಿಕಾರಿಯಾಗಿರಲಿ, ಇಂದೇ ಮಾರ್ಕೆಟ್‌ಸೆನ್ಸ್‌ಗೆ ಸೇರಿ ಮತ್ತು ಸ್ವಚ್ಛ, ಆರೋಗ್ಯಕರ ಸಾರ್ವಜನಿಕ ಸ್ಥಳಗಳಿಗೆ ಕೊಡುಗೆ ನೀಡಿ.",
    signUpNow: "ಈಗಲೇ ಸೈನ್ ಅಪ್ ಮಾಡಿ",
    footer: "© 2024 ಮಾರ್ಕೆಟ್‌ಸೆನ್ಸ್। ಒಟ್ಟಾಗಿ ಸ್ವಚ್ಛ ಸಮುದಾಯಗಳನ್ನು ನಿರ್ಮಿಸುವುದು.",
    selectLanguage: "ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    login: "ಲಾಗಿನ್",
    signUp: "ಸೈನ್ ಅಪ್",
    welcomeBack: "ಮರಳಿ ಸ್ವಾಗತ",
    enterCredentials: "ಮುಂದುವರಿಯಲು ನಿಮ್ಮ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ",
    createAccount: "ಖಾತೆ ರಚಿಸಿ",
    joinInitiative: "ಮಾರ್ಕೆಟ್‌ಸೆನ್ಸ್ ಉಪಕ್ರಮದಲ್ಲಿ ಸೇರಿ",
    email: "ಇಮೇಲ್",
    password: "ಪಾಸ್‌ವರ್ಡ್",
    fullName: "ಪೂರ್ಣ ಹೆಸರು",
    iAmA: "ನಾನು ಒಬ್ಬ",
    marketVendor: "ಮಾರುಕಟ್ಟೆ ಮಾರಾಟಗಾರ",
    municipalityOfficer: "ಮುನ್ಸಿಪಾಲಿಟಿ ಅಧಿಕಾರಿ",
    marketName: "ಮಾರುಕಟ್ಟೆ ಹೆಸರು",
    loggingIn: "ಲಾಗಿನ್ ಆಗುತ್ತಿದೆ...",
    creatingAccount: "ಖಾತೆ ರಚಿಸಲಾಗುತ್ತಿದೆ...",
    wasteManagementSystem: "ಸಾರ್ವಜನಿಕ ಮಾರುಕಟ್ಟೆಗಳಿಗಾಗಿ ತ್ಯಾಜ್ಯ ನಿರ್ವಹಣಾ ವ್ಯವಸ್ಥೆ",
    logout: "ಲಾಗ್‌ಔಟ್",
    photosSubmitted: "ಸಲ್ಲಿಸಿದ ಫೋಟೋಗಳು",
    pointsThisWeek: "ಈ ವಾರದ ಅಂಕಗಳು",
    currentStreak: "ಪ್ರಸ್ತುತ ಸ್ಟ್ರೀಕ್",
    weeklyRank: "ವಾರದ ರ‌್ಯಾಂಕ್",
    vendorDashboard: "ಮಾರಾಟಗಾರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    submitReport: "ವರದಿ ಸಲ್ಲಿಸಿ",
    rankings: "ರ‌್ಯಾಂಕಿಂಗ್‌ಗಳು",
    reportStallStatus: "ಅಂಗಡಿ ಸ್ಥಿತಿಯನ್ನು ವರದಿ ಮಾಡಿ",
    reportStallStatusDesc: "ಸ್ಥಿತಿಯನ್ನು ಆಯ್ಕೆಮಾಡಿ ಮತ್ತು ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ — ಮುನ್ಸಿಪಲ್ ಅಧಿಕಾರಿಗಳು ಪರಿಶೀಲಿಸುತ್ತಾರೆ.",
    stallNumber: "ಅಂಗಡಿ ಸಂಖ್ಯೆ",
    marketArea: "ಮಾರುಕಟ್ಟೆ ಪ್ರದೇಶ",
    selectArea: "ಪ್ರದೇಶ ಆಯ್ಕೆಮಾಡಿ...",
    currentStatus: "ಪ್ರಸ್ತುತ ಸ್ಥಿತಿ",
    clean: "ಸ್ವಚ್ಛ",
    needsCleaning: "ಸ್ವಚ್ಛತೆ ಅಗತ್ಯ",
    overflowing: "ತುಂಬಿ ಹರಿಯುತ್ತಿದೆ",
    comments: "ಟಿಪ್ಪಣಿಗಳು",
    anyNotes: "ಯಾವುದೇ ಟಿಪ್ಪಣಿಗಳು...",
    photoRequired: "ಫೋಟೋ ಅಗತ್ಯ — ಅಪ್‌ಲೋಡ್ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ",
    mySubmissions: "ನನ್ನ ಸಲ್ಲಿಕೆಗಳು",
    noPhotosYet: "ಇನ್ನೂ ಫೋಟೋಗಳಿಲ್ಲ",
    pending: "ಬಾಕಿ",
    reviewed: "ಪರಿಶೀಲಿಸಲಾಗಿದೆ",
    cleaned: "ಸ್ವಚ್ಛಗೊಳಿಸಲಾಗಿದೆ",
    weeklyVendorRankings: "ವಾರದ ಮಾರಾಟಗಾರ ರ‌್ಯಾಂಕಿಂಗ್‌ಗಳು",
    pointsEarned: "ಈ ವಾರ ಗಳಿಸಿದ ಅಂಕಗಳು",
    cleanReports: "ಸ್ವಚ್ಛ ವರದಿಗಳು",
    municipalityDashboard: "ಮುನ್ಸಿಪಾಲಿಟಿ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    monitorManage: "ಮಾರುಕಟ್ಟೆ ಸ್ವಚ್ಛತೆಯನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮತ್ತು ನಿರ್ವಹಿಸಿ",
    awaitingReview: "ಪರಿಶೀಲನೆಗಾಗಿ ಕಾಯುತ್ತಿದೆ",
    underAction: "ಕ್ರಿಯೆಯಲ್ಲಿದೆ",
    completed: "ಪೂರ್ಣಗೊಂಡಿದೆ",
    totalVendors: "ಒಟ್ಟು ಮಾರಾಟಗಾರರು",
    registered: "ನೋಂದಾಯಿತ",
    photoReview: "ಫೋಟೋ ಪರಿಶೀಲನೆ",
    vendorRankings: "ಮಾರಾಟಗಾರ ರ‌್ಯಾಂಕಿಂಗ್‌ಗಳು",
    marketPhotos: "ಮಾರುಕಟ್ಟೆ ಫೋಟೋಗಳು",
    reviewManagePhotos: "ಸಲ್ಲಿಸಿದ ಫೋಟೋಗಳನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತು ನಿರ್ವಹಿಸಿ",
    filterByStatus: "ಸ್ಥಿತಿಯ ಮೂಲಕ ಫಿಲ್ಟರ್ ಮಾಡಿ",
    allPhotos: "ಎಲ್ಲಾ ಫೋಟೋಗಳು",
    filterByArea: "ಪ್ರದೇಶದ ಮೂಲಕ ಫಿಲ್ಟರ್ ಮಾಡಿ",
    allAreas: "ಎಲ್ಲಾ ಪ್ರದೇಶಗಳು",
    vendor: "ಮಾರಾಟಗಾರ",
    uploaded: "ಅಪ್‌ಲೋಡ್ ಆಗಿದೆ",
    score: "ಸ್ಕೋರ್",
    markAsReviewed: "ಪರಿಶೀಲಿಸಲಾಗಿದೆ ಎಂದು ಗುರುತಿಸಿ",
    markAsCleaned: "ಸ್ವಚ್ಛಗೊಳಿಸಲಾಗಿದೆ ಎಂದು ಗುರುತಿಸಿ",
    noPhotosSubmitted: "ಇನ್ನೂ ಯಾವುದೇ ಫೋಟೋಗಳನ್ನು ಸಲ್ಲಿಸಲಾಗಿಲ್ಲ.",
    vendorsRankedByPoints: "ಈ ವಾರ ಗಳಿಸಿದ ಒಟ್ಟು ಅಂಕಗಳ ಮೂಲಕ ಮಾರಾಟಗಾರರನ್ನು ರ‌್ಯಾಂಕ್ ಮಾಡಲಾಗಿದೆ",
    photos: "ಫೋಟೋಗಳು",
    points: "ಅಂಕಗಳು",
    vegetablesSection: "ತರಕಾರಿ ವಿಭಾಗ",
    fruitsSection: "ಹಣ್ಣು ವಿಭಾಗ",
    flowerMarket: "ಹೂವಿನ ಮಾರುಕಟ್ಟೆ",
    fishMarket: "ಮೀನು ಮಾರುಕಟ್ಟೆ",
    meatMarket: "ಮಾಂಸ ಮಾರುಕಟ್ಟೆ",
    pathway: "ಹಾದಿ",
    dustbinZone: "ಕಸದ ಬುಟ್ಟಿ ವಲಯ",
    other: "ಇತರೆ",
    stallPlaceholder: "ಉದಾ., A-12",
    uploadSuccess: "ಧನ್ಯವಾದ — ನಿಮ್ಮ ವರದಿ ದಾಖಲಾಗಿದೆ. ಮುನ್ಸಿಪಾಲಿಟಿ ಪರಿಶೀಲನೆ ಬಾಕಿ.",
    uploadError: "ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡುವಲ್ಲಿ ದೋಷ",
    pleaseUploadImage: "ದಯವಿಟ್ಟು ಚಿತ್ರ ಫೈಲ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    fileSizeLimit: "ಫೈಲ್ ಗಾತ್ರ 5MB ಗಿಂತ ಕಡಿಮೆ ಇರಬೇಕು",
    noAreaSpecified: "ಪ್ರದೇಶ ನಿರ್ದಿಷ್ಟಪಡಿಸಿಲ್ಲ",
    pts: "ಅಂಕಗಳು",
    pt: "ಅಂಕ",
    unknownMarket: "ತಿಳಿಯದ ಮಾರುಕಟ್ಟೆ",
    unknownVendor: "ತಿಳಿಯದು",
    failedToUpdateStatus: "ಸ್ಥಿತಿಯನ್ನು ನವೀಕರಿಸಲು ವಿಫಲ",
    statusUpdatedTo: "ಸ್ಥಿತಿ ನವೀಕರಿಸಲಾಗಿದೆ",
    photoMarkedCleaned: "ಫೋಟೋ ಸ್ವಚ್ಛ ಎಂದು ಗುರುತಿಸಲಾಗಿದೆ — ಮಾರಾಟಗಾರರಿಗೆ +1 ಅಂಕ",
    photoMarkedReviewed: "ಫೋಟೋ ಪರಿಶೀಲಿಸಲಾಗಿದೆ ಎಂದು ಗುರುತಿಸಲಾಗಿದೆ — ಯಾವುದೇ ಅಂಕಗಳಿಲ್ಲ",
    failedToMarkPhoto: "ಫೋಟೋ ಗುರುತಿಸಲು ವಿಫಲ",
    failedToLoadRankings: "ರ‌್ಯಾಂಕಿಂಗ್‌ಗಳನ್ನು ಲೋಡ್ ಮಾಡಲು ವಿಫಲ",
    failedToUpdateRankings: "ರ‌್ಯಾಂಕಿಂಗ್‌ಗಳನ್ನು ನವೀಕರಿಸಲು ವಿಫಲ",
    loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    loadMore: "ಇನ್ನಷ್ಟು ಲೋಡ್ ಮಾಡಿ",
    noInternet: "ಇಂಟರ್ನೆಟ್ ಸಂಪರ್ಕವಿಲ್ಲ",
    uploadRetrying: "ಅಪ್‌ಲೋಡ್ ಮರುಪ್ರಯತ್ನಿಸುತ್ತಿದೆ...",
    uploadQueued: "ಅಪ್‌ಲೋಡ್ ಕ್ಯೂನಲ್ಲಿದೆ",
    uploadFailed: "ಅಪ್‌ಲೋಡ್ ವಿಫಲವಾಗಿದೆ",
    retryUpload: "ಮರುಪ್ರಯತ್ನಿಸಿ",
    retryAll: "ಎಲ್ಲವನ್ನು ಮರುಪ್ರಯತ್ನಿಸಿ",
    uploadingPhoto: "ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    queuedUploads: "ಅಪ್‌ಲೋಡ್‌ಗಳು ಕ್ಯೂನಲ್ಲಿವೆ",
    failedUploads: "ಅಪ್‌ಲೋಡ್‌ಗಳು ವಿಫಲವಾಗಿವೆ",
    dismiss: "ವಜಾಗೊಳಿಸಿ",
    offlineMode: "ಆಫ್‌ಲೈನ್ ಮೋಡ್",
    willRetryWhenOnline: "ಆನ್‌ಲೈನ್ ಆದಾಗ ಮರುಪ್ರಯತ್ನಿಸುತ್ತದೆ",
    serverUnavailable: "ಸರ್ವರ್ ಲಭ್ಯವಿಲ್ಲ",
    retryingAutomatically: "ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಮರುಪ್ರಯತ್ನಿಸುತ್ತಿದೆ...",
    retryCount: "ಮರುಪ್ರಯತ್ನಗಳು",
    myReviews: "ನನ್ನ ವಿಮರ್ಶೆಗಳು",
    noPendingPhotos: "ಪರಿಶೀಲಿಸಲು ಬಾಕಿ ಫೋಟೋಗಳಿಲ್ಲ",
    noReviewsYet: "ನೀವು ಇನ್ನೂ ಯಾವುದೇ ಫೋಟೋಗಳನ್ನು ಪರಿಶೀಲಿಸಿಲ್ಲ",
  },
  ml: {
    cleanMarketInitiative: "ശുദ്ധ മാർക്കറ്റ് സംരംഭം",
    appName: "UrbanEye AI",
    tagline: "ശുദ്ധവും ആരോഗ്യകരവുമായ പൊതു മാർക്കറ്റുകൾക്കായി വിൽപ്പനക്കാരെ ഓഫീസർമാരുമായി ബന്ധിപ്പിക്കുന്ന മുനിസിപ്പൽ മാലിന്യ മാനേജ്മെന്റ് സിസ്റ്റം",
    getStarted: "ആരംഭിക്കുക",
    installApp: "ആപ്പ് ഇൻസ്റ്റാൾ ചെയ്യുക",
    howItWorks: "ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു",
    howItWorksDesc: "മാർക്കറ്റ് ശുചിത്വം നിലനിർത്താനുള്ള ലളിതമായ മൂന്ന്-ഘട്ട പ്രക്രിയ",
    vendorsUpload: "വിൽപ്പനക്കാർ അപ്‌ലോഡ് ചെയ്യുക",
    vendorsUploadDesc: "മാർക്കറ്റ് വിൽപ്പനക്കാർ അവരുടെ പ്രദേശങ്ങളുടെ ഫോട്ടോ എടുത്ത് മാലിന്യം റിപ്പോർട്ട് ചെയ്യുന്നതിനോ ശുചിത്വം പ്രദർശിപ്പിക്കുന്നതിനോ ചിത്രങ്ങൾ അപ്‌ലോഡ് ചെയ്യുന്നു",
    officersReview: "ഓഫീസർമാർ അവലോകനം ചെയ്യുക",
    officersReviewDesc: "മുനിസിപ്പാലിറ്റി ഓഫീസർമാർ സമർപ്പണങ്ങൾ അവലോകനം ചെയ്യുകയും ശ്രദ്ധ ആവശ്യമായ പ്രദേശങ്ങളിലേക്ക് ക്ലീനിംഗ് സിബ്ബന്ദിയെ അയക്കുകയും ചെയ്യുന്നു",
    vendorsGetRanked: "വിൽപ്പനക്കാർക്ക് റാങ്ക് ലഭിക്കുന്നു",
    vendorsGetRankedDesc: "സജീവ വിൽപ്പനക്കാർക്ക് ആഴ്ചതോറും റാങ്ക് ലഭിക്കുന്നു, ഏറ്റവും സജീവമായ വിൽപ്പനക്കാരന് \"ആഴ്ചയിലെ ശുദ്ധ വിൽപ്പനക്കാരൻ\" കിരീടം ലഭിക്കുന്നു",
    readyToJoin: "ചേരാൻ തയ്യാറാണോ?",
    readyToJoinDesc: "നിങ്ങൾ മാർക്കറ്റ് വിൽപ്പനക്കാരനായാലും മുനിസിപ്പാലിറ്റി ഓഫീസറായാലും, ഇന്ന് തന്നെ മാർക്കറ്റ്സെൻസിൽ ചേർന്ന് ശുദ്ധവും ആരോഗ്യകരവുമായ പൊതു ഇടങ്ങളിലേക്ക് സംഭാവന ചെയ്യൂ.",
    signUpNow: "ഇപ്പോൾ സൈൻ അപ്പ് ചെയ്യുക",
    footer: "© 2024 മാർക്കറ്റ്സെൻസ്। ഒരുമിച്ച് ശുദ്ധമായ സമൂഹങ്ങൾ കെട്ടിപ്പടുക്കൽ.",
    selectLanguage: "ഭാഷ തിരഞ്ഞെടുക്കുക",
    login: "ലോഗിൻ",
    signUp: "സൈൻ അപ്പ്",
    welcomeBack: "തിരികെ സ്വാഗതം",
    enterCredentials: "തുടരാൻ നിങ്ങളുടെ വിവരങ്ങൾ നൽകുക",
    createAccount: "അക്കൗണ്ട് സൃഷ്ടിക്കുക",
    joinInitiative: "മാർക്കറ്റ്സെൻസ് സംരംഭത്തിൽ ചേരുക",
    email: "ഇമെയിൽ",
    password: "പാസ്‌വേഡ്",
    fullName: "പൂർണ്ണ പേര്",
    iAmA: "ഞാൻ ഒരു",
    marketVendor: "മാർക്കറ്റ് വിൽപ്പനക്കാരൻ",
    municipalityOfficer: "മുനിസിപ്പാലിറ്റി ഓഫീസർ",
    marketName: "മാർക്കറ്റ് പേര്",
    loggingIn: "ലോഗിൻ ചെയ്യുന്നു...",
    creatingAccount: "അക്കൗണ്ട് സൃഷ്ടിക്കുന്നു...",
    wasteManagementSystem: "പൊതു മാർക്കറ്റുകൾക്കുള്ള മാലിന്യ മാനേജ്മെന്റ് സിസ്റ്റം",
    logout: "ലോഗൗട്ട്",
    photosSubmitted: "സമർപ്പിച്ച ഫോട്ടോകൾ",
    pointsThisWeek: "ഈ ആഴ്ച പോയിന്റുകൾ",
    currentStreak: "നിലവിലെ സ്ട്രീക്ക്",
    weeklyRank: "ആഴ്ചയിലെ റാങ്ക്",
    vendorDashboard: "വിൽപ്പനക്കാരന്റെ ഡാഷ്ബോർഡ്",
    submitReport: "റിപ്പോർട്ട് സമർപ്പിക്കുക",
    rankings: "റാങ്കിംഗുകൾ",
    reportStallStatus: "സ്റ്റാൾ സ്ഥിതി റിപ്പോർട്ട് ചെയ്യുക",
    reportStallStatusDesc: "സ്ഥിതി തിരഞ്ഞെടുത്ത് ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക — മുനിസിപ്പൽ ഓഫീസർമാർ അവലോകനം ചെയ്യും.",
    stallNumber: "സ്റ്റാൾ നമ്പർ",
    marketArea: "മാർക്കറ്റ് പ്രദേശം",
    selectArea: "പ്രദേശം തിരഞ്ഞെടുക്കുക...",
    currentStatus: "നിലവിലെ സ്ഥിതി",
    clean: "ശുദ്ധം",
    needsCleaning: "ശുദ്ധീകരണം ആവശ്യമാണ്",
    overflowing: "കവിഞ്ഞൊഴുകുന്നു",
    comments: "അഭിപ്രായങ്ങൾ",
    anyNotes: "എന്തെങ്കിലും കുറിപ്പുകൾ...",
    photoRequired: "ഫോട്ടോ ആവശ്യമാണ് — അപ്‌ലോഡ് ചെയ്യാൻ ക്ലിക്ക് ചെയ്യുക",
    mySubmissions: "എന്റെ സമർപ്പണങ്ങൾ",
    noPhotosYet: "ഇതുവരെ ഫോട്ടോകളില്ല",
    pending: "തീർപ്പുകൽപ്പിക്കാത്ത",
    reviewed: "അവലോകനം ചെയ്തു",
    cleaned: "ശുദ്ധീകരിച്ചു",
    weeklyVendorRankings: "ആഴ്ചയിലെ വിൽപ്പനക്കാരുടെ റാങ്കിംഗുകൾ",
    pointsEarned: "ഈ ആഴ്ച നേടിയ പോയിന്റുകൾ",
    cleanReports: "ശുദ്ധമായ റിപ്പോർട്ടുകൾ",
    municipalityDashboard: "മുനിസിപ്പാലിറ്റി ഡാഷ്ബോർഡ്",
    monitorManage: "മാർക്കറ്റ് ശുചിത്വം നിരീക്ഷിക്കുകയും നിയന്ത്രിക്കുകയും ചെയ്യുക",
    awaitingReview: "അവലോകനത്തിനായി കാത്തിരിക്കുന്നു",
    underAction: "നടപടിയിൽ",
    completed: "പൂർത്തിയായി",
    totalVendors: "ആകെ വിൽപ്പനക്കാർ",
    registered: "രജിസ്റ്റർ ചെയ്തത്",
    photoReview: "ഫോട്ടോ അവലോകനം",
    vendorRankings: "വിൽപ്പനക്കാരുടെ റാങ്കിംഗുകൾ",
    marketPhotos: "മാർക്കറ്റ് ഫോട്ടോകൾ",
    reviewManagePhotos: "സമർപ്പിച്ച ഫോട്ടോകൾ അവലോകനം ചെയ്ത് നിയന്ത്രിക്കുക",
    filterByStatus: "സ്ഥിതി അനുസരിച്ച് ഫിൽട്ടർ ചെയ്യുക",
    allPhotos: "എല്ലാ ഫോട്ടോകളും",
    filterByArea: "പ്രദേശം അനുസരിച്ച് ഫിൽട്ടർ ചെയ്യുക",
    allAreas: "എല്ലാ പ്രദേശങ്ങളും",
    vendor: "വിൽപ്പനക്കാരൻ",
    uploaded: "അപ്‌ലോഡ് ചെയ്തു",
    score: "സ്കോർ",
    markAsReviewed: "അവലോകനം ചെയ്തതായി അടയാളപ്പെടുത്തുക",
    markAsCleaned: "ശുദ്ധീകരിച്ചതായി അടയാളപ്പെടുത്തുക",
    noPhotosSubmitted: "ഇതുവരെ ഫോട്ടോകളൊന്നും സമർപ്പിച്ചിട്ടില്ല.",
    vendorsRankedByPoints: "ഈ ആഴ്ച നേടിയ ആകെ പോയിന്റുകൾ അനുസരിച്ച് വിൽപ്പനക്കാരെ റാങ്ക് ചെയ്തിരിക്കുന്നു",
    photos: "ഫോട്ടോകൾ",
    points: "പോയിന്റുകൾ",
    vegetablesSection: "പച്ചക്കറി വിഭാഗം",
    fruitsSection: "പഴം വിഭാഗം",
    flowerMarket: "പൂ മാർക്കറ്റ്",
    fishMarket: "മീൻ മാർക്കറ്റ്",
    meatMarket: "മാംസ മാർക്കറ്റ്",
    pathway: "പാത",
    dustbinZone: "ചവറ്റുകുട്ട മേഖല",
    other: "മറ്റുള്ളവ",
    stallPlaceholder: "ഉദാ., A-12",
    uploadSuccess: "നന്ദി — നിങ്ങളുടെ റിപ്പോർട്ട് രേഖപ്പെടുത്തി. മുനിസിപ്പൽ അവലോകനം ബാക്കി.",
    uploadError: "ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുന്നതിൽ പിശക്",
    pleaseUploadImage: "ദയവായി ഒരു ചിത്ര ഫയൽ അപ്‌ലോഡ് ചെയ്യുക",
    fileSizeLimit: "ഫയൽ സൈസ് 5MB-ൽ കുറവായിരിക്കണം",
    noAreaSpecified: "പ്രദേശം വ്യക്തമാക്കിയിട്ടില്ല",
    pts: "പോയിന്റുകൾ",
    pt: "പോയിന്റ്",
    unknownMarket: "അജ്ഞാത മാർക്കറ്റ്",
    unknownVendor: "അജ്ഞാതം",
    failedToUpdateStatus: "സ്ഥിതി അപ്ഡേറ്റ് ചെയ്യുന്നതിൽ പരാജയപ്പെട്ടു",
    statusUpdatedTo: "സ്ഥിതി അപ്ഡേറ്റ് ചെയ്തു",
    photoMarkedCleaned: "ഫോട്ടോ ശുദ്ധമായി അടയാളപ്പെടുത്തി — വിൽപ്പനക്കാരന് +1 പോയിന്റ്",
    photoMarkedReviewed: "ഫോട്ടോ അവലോകനം ചെയ്തതായി അടയാളപ്പെടുത്തി — പോയിന്റുകളില്ല",
    failedToMarkPhoto: "ഫോട്ടോ അടയാളപ്പെടുത്തുന്നതിൽ പരാജയപ്പെട്ടു",
    failedToLoadRankings: "റാങ്കിംഗുകൾ ലോഡ് ചെയ്യുന്നതിൽ പരാജയപ്പെട്ടു",
    failedToUpdateRankings: "റാങ്കിംഗുകൾ അപ്ഡേറ്റ് ചെയ്യുന്നതിൽ പരാജയപ്പെട്ടു",
    loading: "ലോഡ് ചെയ്യുന്നു...",
    loadMore: "കൂടുതൽ ലോഡ് ചെയ്യുക",
    noInternet: "ഇന്റർനെറ്റ് കണക്ഷൻ ഇല്ല",
    uploadRetrying: "അപ്‌ലോഡ് വീണ്ടും ശ്രമിക്കുന്നു...",
    uploadQueued: "അപ്‌ലോഡ് ക്യൂവിൽ",
    uploadFailed: "അപ്‌ലോഡ് പരാജയപ്പെട്ടു",
    retryUpload: "വീണ്ടും ശ്രമിക്കുക",
    retryAll: "എല്ലാം വീണ്ടും ശ്രമിക്കുക",
    uploadingPhoto: "ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുന്നു...",
    queuedUploads: "അപ്‌ലോഡുകൾ ക്യൂവിൽ",
    failedUploads: "അപ്‌ലോഡുകൾ പരാജയപ്പെട്ടു",
    dismiss: "നിരസിക്കുക",
    offlineMode: "ഓഫ്‌ലൈൻ മോഡ്",
    willRetryWhenOnline: "ഓൺലൈനിൽ ആയിരിക്കുമ്പോൾ വീണ്ടും ശ്രമിക്കും",
    serverUnavailable: "സെർവർ ലഭ്യമല്ല",
    retryingAutomatically: "ഓട്ടോമാറ്റിക്കായി വീണ്ടും ശ്രമിക്കുന്നു...",
    retryCount: "വീണ്ടും ശ്രമങ്ങൾ",
    myReviews: "എന്റെ അവലോകനങ്ങൾ",
    noPendingPhotos: "അവലോകനം ചെയ്യാൻ തീർപ്പാക്കാത്ത ഫോട്ടോകൾ ഇല്ല",
    noReviewsYet: "നിങ്ങൾ ഇതുവരെ ഫോട്ടോകളൊന്നും അവലോകനം ചെയ്തിട്ടില്ല",
  },
  pa: {
    cleanMarketInitiative: "ਸਾਫ਼ ਮੰਡੀ ਪਹਿਲਕਦਮੀ",
    appName: "UrbanEye AI",
    tagline: "ਸਾਫ਼, ਸਿਹਤਮੰਦ ਜਨਤਕ ਮੰਡੀਆਂ ਲਈ ਵਿਕਰੇਤਾਵਾਂ ਨੂੰ ਅਧਿਕਾਰੀਆਂ ਨਾਲ ਜੋੜਨ ਵਾਲੀ ਮਿਊਂਸਪਲ ਕੂੜਾ ਪ੍ਰਬੰਧਨ ਪ੍ਰਣਾਲੀ",
    getStarted: "ਸ਼ੁਰੂ ਕਰੋ",
    installApp: "ਐਪ ਇੰਸਟਾਲ ਕਰੋ",
    howItWorks: "ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ",
    howItWorksDesc: "ਮੰਡੀ ਦੀ ਸਫ਼ਾਈ ਬਣਾਈ ਰੱਖਣ ਲਈ ਇੱਕ ਸਧਾਰਨ ਤਿੰਨ-ਕਦਮ ਪ੍ਰਕਿਰਿਆ",
    vendorsUpload: "ਵਿਕਰੇਤਾ ਅਪਲੋਡ ਕਰੋ",
    vendorsUploadDesc: "ਮੰਡੀ ਦੇ ਵਿਕਰੇਤਾ ਆਪਣੇ ਖੇਤਰਾਂ ਦੀਆਂ ਫੋਟੋਆਂ ਲੈਂਦੇ ਹਨ ਅਤੇ ਕੂੜਾ ਰਿਪੋਰਟ ਕਰਨ ਜਾਂ ਸਫ਼ਾਈ ਦਿਖਾਉਣ ਲਈ ਚਿੱਤਰ ਅਪਲੋਡ ਕਰਦੇ ਹਨ",
    officersReview: "ਅਧਿਕਾਰੀ ਸਮੀਖਿਆ ਕਰੋ",
    officersReviewDesc: "ਮਿਊਂਸਪੈਲਿਟੀ ਅਧਿਕਾਰੀ ਸਬਮਿਸ਼ਨਾਂ ਦੀ ਸਮੀਖਿਆ ਕਰਦੇ ਹਨ ਅਤੇ ਜਿਨ੍ਹਾਂ ਖੇਤਰਾਂ ਵੱਲ ਧਿਆਨ ਦੇਣ ਦੀ ਲੋੜ ਹੈ ਉੱਥੇ ਸਫ਼ਾਈ ਕਰਮਚਾਰੀ ਭੇਜਦੇ ਹਨ",
    vendorsGetRanked: "ਵਿਕਰੇਤਾਵਾਂ ਨੂੰ ਰੈਂਕ ਮਿਲਦੀ ਹੈ",
    vendorsGetRankedDesc: "ਸਰਗਰਮ ਵਿਕਰੇਤਾਵਾਂ ਨੂੰ ਹਫ਼ਤਾਵਾਰੀ ਰੈਂਕ ਮਿਲਦੀ ਹੈ, ਸਭ ਤੋਂ ਵੱਧ ਸਰਗਰਮ ਵਿਕਰੇਤਾ ਨੂੰ \"ਹਫ਼ਤੇ ਦਾ ਸਾਫ਼ ਵਿਕਰੇਤਾ\" ਦਾ ਤਾਜ ਮਿਲਦਾ ਹੈ",
    readyToJoin: "ਸ਼ਾਮਲ ਹੋਣ ਲਈ ਤਿਆਰ?",
    readyToJoinDesc: "ਭਾਵੇਂ ਤੁਸੀਂ ਮੰਡੀ ਦੇ ਵਿਕਰੇਤਾ ਹੋ ਜਾਂ ਮਿਊਂਸਪੈਲਿਟੀ ਅਧਿਕਾਰੀ, ਅੱਜ ਹੀ ਮਾਰਕੀਟਸੈਂਸ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਵੋ ਅਤੇ ਸਾਫ਼, ਸਿਹਤਮੰਦ ਜਨਤਕ ਥਾਵਾਂ ਵਿੱਚ ਯੋਗਦਾਨ ਪਾਓ।",
    signUpNow: "ਹੁਣੇ ਸਾਈਨ ਅੱਪ ਕਰੋ",
    footer: "© 2024 ਮਾਰਕੀਟਸੈਂਸ। ਮਿਲ ਕੇ ਸਾਫ਼ ਭਾਈਚਾਰੇ ਬਣਾਉਣਾ।",
    selectLanguage: "ਭਾਸ਼ਾ ਚੁਣੋ",
    login: "ਲੌਗਿਨ",
    signUp: "ਸਾਈਨ ਅੱਪ",
    welcomeBack: "ਵਾਪਸ ਸੁਆਗਤ ਹੈ",
    enterCredentials: "ਜਾਰੀ ਰੱਖਣ ਲਈ ਆਪਣੇ ਵੇਰਵੇ ਦਾਖਲ ਕਰੋ",
    createAccount: "ਖਾਤਾ ਬਣਾਓ",
    joinInitiative: "ਮਾਰਕੀਟਸੈਂਸ ਪਹਿਲਕਦਮੀ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਵੋ",
    email: "ਈਮੇਲ",
    password: "ਪਾਸਵਰਡ",
    fullName: "ਪੂਰਾ ਨਾਮ",
    iAmA: "ਮੈਂ ਇੱਕ",
    marketVendor: "ਮੰਡੀ ਵਿਕਰੇਤਾ",
    municipalityOfficer: "ਮਿਊਂਸਪੈਲਿਟੀ ਅਧਿਕਾਰੀ",
    marketName: "ਮੰਡੀ ਦਾ ਨਾਮ",
    loggingIn: "ਲੌਗਿਨ ਹੋ ਰਿਹਾ ਹੈ...",
    creatingAccount: "ਖਾਤਾ ਬਣ ਰਿਹਾ ਹੈ...",
    wasteManagementSystem: "ਜਨਤਕ ਮੰਡੀਆਂ ਲਈ ਕੂੜਾ ਪ੍ਰਬੰਧਨ ਪ੍ਰਣਾਲੀ",
    logout: "ਲੌਗਆਊਟ",
    photosSubmitted: "ਜਮ੍ਹਾਂ ਕੀਤੀਆਂ ਫੋਟੋਆਂ",
    pointsThisWeek: "ਇਸ ਹਫ਼ਤੇ ਅੰਕ",
    currentStreak: "ਮੌਜੂਦਾ ਲੜੀ",
    weeklyRank: "ਹਫ਼ਤਾਵਾਰੀ ਰੈਂਕ",
    vendorDashboard: "ਵਿਕਰੇਤਾ ਡੈਸ਼ਬੋਰਡ",
    submitReport: "ਰਿਪੋਰਟ ਜਮ੍ਹਾਂ ਕਰੋ",
    rankings: "ਰੈਂਕਿੰਗ",
    reportStallStatus: "ਸਟਾਲ ਦੀ ਸਥਿਤੀ ਰਿਪੋਰਟ ਕਰੋ",
    reportStallStatusDesc: "ਸਥਿਤੀ ਚੁਣੋ ਅਤੇ ਫੋਟੋ ਅਪਲੋਡ ਕਰੋ — ਮਿਊਂਸਪਲ ਅਧਿਕਾਰੀ ਸਮੀਖਿਆ ਕਰਨਗੇ।",
    stallNumber: "ਸਟਾਲ ਨੰਬਰ",
    marketArea: "ਮੰਡੀ ਖੇਤਰ",
    selectArea: "ਖੇਤਰ ਚੁਣੋ...",
    currentStatus: "ਮੌਜੂਦਾ ਸਥਿਤੀ",
    clean: "ਸਾਫ਼",
    needsCleaning: "ਸਫ਼ਾਈ ਚਾਹੀਦੀ ਹੈ",
    overflowing: "ਓਵਰਫਲੋ",
    comments: "ਟਿੱਪਣੀਆਂ",
    anyNotes: "ਕੋਈ ਨੋਟਸ...",
    photoRequired: "ਫੋਟੋ ਲੋੜੀਂਦੀ — ਅਪਲੋਡ ਕਰਨ ਲਈ ਕਲਿੱਕ ਕਰੋ",
    mySubmissions: "ਮੇਰੀਆਂ ਜਮ੍ਹਾਂ",
    noPhotosYet: "ਅਜੇ ਕੋਈ ਫੋਟੋਆਂ ਨਹੀਂ",
    pending: "ਬਕਾਇਆ",
    reviewed: "ਸਮੀਖਿਆ ਕੀਤੀ",
    cleaned: "ਸਾਫ਼ ਕੀਤਾ",
    weeklyVendorRankings: "ਹਫ਼ਤਾਵਾਰੀ ਵਿਕਰੇਤਾ ਰੈਂਕਿੰਗ",
    pointsEarned: "ਇਸ ਹਫ਼ਤੇ ਕਮਾਏ ਅੰਕ",
    cleanReports: "ਸਾਫ਼ ਰਿਪੋਰਟਾਂ",
    municipalityDashboard: "ਮਿਊਂਸਪੈਲਿਟੀ ਡੈਸ਼ਬੋਰਡ",
    monitorManage: "ਮੰਡੀ ਦੀ ਸਫ਼ਾਈ ਦੀ ਨਿਗਰਾਨੀ ਅਤੇ ਪ੍ਰਬੰਧਨ ਕਰੋ",
    awaitingReview: "ਸਮੀਖਿਆ ਦੀ ਉਡੀਕ",
    underAction: "ਕਾਰਵਾਈ ਅਧੀਨ",
    completed: "ਪੂਰਾ ਹੋਇਆ",
    totalVendors: "ਕੁੱਲ ਵਿਕਰੇਤਾ",
    registered: "ਰਜਿਸਟਰਡ",
    photoReview: "ਫੋਟੋ ਸਮੀਖਿਆ",
    vendorRankings: "ਵਿਕਰੇਤਾ ਰੈਂਕਿੰਗ",
    marketPhotos: "ਮੰਡੀ ਫੋਟੋਆਂ",
    reviewManagePhotos: "ਜਮ੍ਹਾਂ ਕੀਤੀਆਂ ਫੋਟੋਆਂ ਦੀ ਸਮੀਖਿਆ ਅਤੇ ਪ੍ਰਬੰਧਨ ਕਰੋ",
    filterByStatus: "ਸਥਿਤੀ ਦੁਆਰਾ ਫਿਲਟਰ ਕਰੋ",
    allPhotos: "ਸਾਰੀਆਂ ਫੋਟੋਆਂ",
    filterByArea: "ਖੇਤਰ ਦੁਆਰਾ ਫਿਲਟਰ ਕਰੋ",
    allAreas: "ਸਾਰੇ ਖੇਤਰ",
    vendor: "ਵਿਕਰੇਤਾ",
    uploaded: "ਅਪਲੋਡ ਕੀਤਾ",
    score: "ਸਕੋਰ",
    markAsReviewed: "ਸਮੀਖਿਆ ਕੀਤੀ ਵਜੋਂ ਮਾਰਕ ਕਰੋ",
    markAsCleaned: "ਸਾਫ਼ ਵਜੋਂ ਮਾਰਕ ਕਰੋ",
    noPhotosSubmitted: "ਅਜੇ ਕੋਈ ਫੋਟੋਆਂ ਜਮ੍ਹਾਂ ਨਹੀਂ ਕੀਤੀਆਂ ਗਈਆਂ।",
    vendorsRankedByPoints: "ਇਸ ਹਫ਼ਤੇ ਕਮਾਏ ਕੁੱਲ ਅੰਕਾਂ ਦੁਆਰਾ ਵਿਕਰੇਤਾਵਾਂ ਨੂੰ ਰੈਂਕ ਕੀਤਾ ਗਿਆ",
    photos: "ਫੋਟੋਆਂ",
    points: "ਅੰਕ",
    vegetablesSection: "ਸਬਜ਼ੀ ਸੈਕਸ਼ਨ",
    fruitsSection: "ਫਲ ਸੈਕਸ਼ਨ",
    flowerMarket: "ਫੁੱਲ ਮੰਡੀ",
    fishMarket: "ਮੱਛੀ ਮੰਡੀ",
    meatMarket: "ਮੀਟ ਮੰਡੀ",
    pathway: "ਰਸਤਾ",
    dustbinZone: "ਕੂੜੇਦਾਨ ਜ਼ੋਨ",
    other: "ਹੋਰ",
    stallPlaceholder: "ਜਿਵੇਂ, A-12",
    uploadSuccess: "ਧੰਨਵਾਦ — ਤੁਹਾਡੀ ਰਿਪੋਰਟ ਦਰਜ ਹੋ ਗਈ ਹੈ। ਮਿਊਂਸਪਲ ਸਮੀਖਿਆ ਬਕਾਇਆ.",
    uploadError: "ਫੋਟੋ ਅਪਲੋਡ ਕਰਨ ਵਿੱਚ ਗਲਤੀ",
    pleaseUploadImage: "ਕਿਰਪਾ ਕਰਕੇ ਇੱਕ ਚਿੱਤਰ ਫਾਈਲ ਅਪਲੋਡ ਕਰੋ",
    fileSizeLimit: "ਫਾਈਲ ਦਾ ਆਕਾਰ 5MB ਤੋਂ ਘੱਟ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ",
    noAreaSpecified: "ਖੇਤਰ ਨਿਰਧਾਰਿਤ ਨਹੀਂ",
    pts: "ਅੰਕ",
    pt: "ਅੰਕ",
    unknownMarket: "ਅਣਜਾਣ ਮੰਡੀ",
    unknownVendor: "ਅਣਜਾਣ",
    failedToUpdateStatus: "ਸਥਿਤੀ ਅੱਪਡੇਟ ਕਰਨ ਵਿੱਚ ਅਸਫਲ",
    statusUpdatedTo: "ਸਥਿਤੀ ਅੱਪਡੇਟ ਹੋਈ",
    photoMarkedCleaned: "ਫੋਟੋ ਸਾਫ਼ ਵਜੋਂ ਚਿੰਨ੍ਹਿਤ — ਵਿਕਰੇਤਾ ਨੂੰ +1 ਅੰਕ",
    photoMarkedReviewed: "ਫੋਟੋ ਸਮੀਖਿਆ ਕੀਤੀ ਵਜੋਂ ਚਿੰਨ੍ਹਿਤ — ਕੋਈ ਅੰਕ ਨਹੀਂ",
    failedToMarkPhoto: "ਫੋਟੋ ਚਿੰਨ੍ਹਿਤ ਕਰਨ ਵਿੱਚ ਅਸਫਲ",
    failedToLoadRankings: "ਰੈਂਕਿੰਗ ਲੋਡ ਕਰਨ ਵਿੱਚ ਅਸਫਲ",
    failedToUpdateRankings: "ਰੈਂਕਿੰਗ ਅੱਪਡੇਟ ਕਰਨ ਵਿੱਚ ਅਸਫਲ",
    loading: "ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...",
    loadMore: "ਹੋਰ ਲੋਡ ਕਰੋ",
    noInternet: "ਇੰਟਰਨੈੱਟ ਕਨੈਕਸ਼ਨ ਨਹੀਂ",
    uploadRetrying: "ਅਪਲੋਡ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਹੋ ਰਹੀ ਹੈ...",
    uploadQueued: "ਅਪਲੋਡ ਕਤਾਰ ਵਿੱਚ ਹੈ",
    uploadFailed: "ਅਪਲੋਡ ਅਸਫਲ",
    retryUpload: "ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ",
    retryAll: "ਸਾਰੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ",
    uploadingPhoto: "ਫੋਟੋ ਅਪਲੋਡ ਹੋ ਰਹੀ ਹੈ...",
    queuedUploads: "ਅਪਲੋਡ ਕਤਾਰ ਵਿੱਚ ਹਨ",
    failedUploads: "ਅਪਲੋਡ ਅਸਫਲ ਹੋਏ",
    dismiss: "ਰੱਦ ਕਰੋ",
    offlineMode: "ਔਫਲਾਈਨ ਮੋਡ",
    willRetryWhenOnline: "ਔਨਲਾਈਨ ਹੋਣ 'ਤੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਹੋਵੇਗੀ",
    serverUnavailable: "ਸਰਵਰ ਉਪਲਬਧ ਨਹੀਂ",
    retryingAutomatically: "ਆਟੋਮੈਟਿਕ ਤੌਰ 'ਤੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਹੋ ਰਹੀ ਹੈ...",
    retryCount: "ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ਾਂ",
    myReviews: "ਮੇਰੀਆਂ ਸਮੀਖਿਆਵਾਂ",
    noPendingPhotos: "ਸਮੀਖਿਆ ਲਈ ਕੋਈ ਬਕਾਇਆ ਫੋਟੋ ਨਹੀਂ",
    noReviewsYet: "ਤੁਸੀਂ ਅਜੇ ਕੋਈ ਫੋਟੋ ਸਮੀਖਿਆ ਨਹੀਂ ਕੀਤੀ",
  },
  or: {
    cleanMarketInitiative: "ପରିଷ୍କାର ବଜାର ପଦକ୍ଷେପ",
    appName: "UrbanEye AI",
    tagline: "ପରିଷ୍କାର, ସ୍ୱାସ୍ଥ୍ୟକର ସାର୍ବଜନୀନ ବଜାର ପାଇଁ ବିକ୍ରେତାମାନଙ୍କୁ ଅଧିକାରୀଙ୍କ ସହ ସଂଯୋଗ କରୁଥିବା ମ୍ୟୁନିସିପାଲ୍ ବର୍ଜ୍ୟ ପରିଚାଳନା ବ୍ୟବସ୍ଥା",
    getStarted: "ଆରମ୍ଭ କରନ୍ତୁ",
    installApp: "ଆପ୍ ଇନଷ୍ଟଲ୍ କରନ୍ତୁ",
    howItWorks: "ଏହା କିପରି କାମ କରେ",
    howItWorksDesc: "ବଜାର ପରିଷ୍କାରତା ବଜାୟ ରଖିବା ପାଇଁ ଏକ ସରଳ ତିନି-ପଦକ୍ଷେପ ପ୍ରକ୍ରିୟା",
    vendorsUpload: "ବିକ୍ରେତାମାନେ ଅପଲୋଡ୍ କରନ୍ତୁ",
    vendorsUploadDesc: "ବଜାର ବିକ୍ରେତାମାନେ ସେମାନଙ୍କ ଅଞ୍ଚଳର ଫଟୋ ଉଠାନ୍ତି ଏବଂ ବର୍ଜ୍ୟ ରିପୋର୍ଟ କରିବାକୁ କିମ୍ବା ପରିଷ୍କାରତା ପ୍ରଦର୍ଶନ କରିବାକୁ ଚିତ୍ର ଅପଲୋଡ୍ କରନ୍ତି",
    officersReview: "ଅଧିକାରୀମାନେ ସମୀକ୍ଷା କରନ୍ତୁ",
    officersReviewDesc: "ମ୍ୟୁନିସିପାଲିଟି ଅଧିକାରୀମାନେ ଦାଖଲଗୁଡ଼ିକ ସମୀକ୍ଷା କରନ୍ତି ଏବଂ ଯେଉଁ ଅଞ୍ଚଳଗୁଡ଼ିକୁ ଧ୍ୟାନ ଦେବା ଆବଶ୍ୟକ ସେଠାରେ ସଫେଇ କର୍ମଚାରୀ ପଠାନ୍ତି",
    vendorsGetRanked: "ବିକ୍ରେତାମାନେ ର‍୍ୟାଙ୍କ ପାଆନ୍ତି",
    vendorsGetRankedDesc: "ସକ୍ରିୟ ବିକ୍ରେତାମାନେ ସାପ୍ତାହିକ ର‍୍ୟାଙ୍କ ପାଆନ୍ତି, ସବୁଠାରୁ ସକ୍ରିୟ ବିକ୍ରେତାଙ୍କୁ \"ସପ୍ତାହର ପରିଷ୍କାର ବିକ୍ରେତା\" ମୁକୁଟ ଦିଆଯାଏ",
    readyToJoin: "ଯୋଗ ଦେବାକୁ ପ୍ରସ୍ତୁତ?",
    readyToJoinDesc: "ଆପଣ ବଜାର ବିକ୍ରେତା ହୁଅନ୍ତୁ କିମ୍ବା ମ୍ୟୁନିସିପାଲିଟି ଅଧିକାରୀ, ଆଜି ହିଁ ମାର୍କେଟସେନ୍ସରେ ଯୋଗ ଦିଅନ୍ତୁ ଏବଂ ପରିଷ୍କାର, ସ୍ୱାସ୍ଥ୍ୟକର ସାର୍ବଜନୀନ ସ୍ଥାନଗୁଡ଼ିକରେ ଯୋଗଦାନ କରନ୍ତୁ।",
    signUpNow: "ବର୍ତ୍ତମାନ ସାଇନ୍ ଅପ୍ କରନ୍ତୁ",
    footer: "© 2024 ମାର୍କେଟସେନ୍ସ। ଏକାଠି ପରିଷ୍କାର ସମୁଦାୟ ନିର୍ମାଣ।",
    selectLanguage: "ଭାଷା ବାଛନ୍ତୁ",
    login: "ଲଗଇନ୍",
    signUp: "ସାଇନ୍ ଅପ୍",
    welcomeBack: "ପୁଣି ସ୍ୱାଗତ",
    enterCredentials: "ଜାରି ରଖିବାକୁ ଆପଣଙ୍କ ବିବରଣୀ ଦିଅନ୍ତୁ",
    createAccount: "ଆକାଉଣ୍ଟ ସୃଷ୍ଟି କରନ୍ତୁ",
    joinInitiative: "ମାର୍କେଟସେନ୍ସ ପଦକ୍ଷେପରେ ଯୋଗ ଦିଅନ୍ତୁ",
    email: "ଇମେଲ୍",
    password: "ପାସୱାର୍ଡ",
    fullName: "ପୂର୍ଣ୍ଣ ନାମ",
    iAmA: "ମୁଁ ଜଣେ",
    marketVendor: "ବଜାର ବିକ୍ରେତା",
    municipalityOfficer: "ମ୍ୟୁନିସିପାଲିଟି ଅଧିକାରୀ",
    marketName: "ବଜାର ନାମ",
    loggingIn: "ଲଗଇନ୍ ହେଉଛି...",
    creatingAccount: "ଆକାଉଣ୍ଟ ସୃଷ୍ଟି ହେଉଛି...",
    wasteManagementSystem: "ସାର୍ବଜନୀନ ବଜାର ପାଇଁ ବର୍ଜ୍ୟ ପରିଚାଳନା ବ୍ୟବସ୍ଥା",
    logout: "ଲଗଆଉଟ୍",
    photosSubmitted: "ଦାଖଲ ହୋଇଥିବା ଫଟୋ",
    pointsThisWeek: "ଏହି ସପ୍ତାହରେ ପଏଣ୍ଟ",
    currentStreak: "ବର୍ତ୍ତମାନ ଷ୍ଟ୍ରିକ୍",
    weeklyRank: "ସାପ୍ତାହିକ ର‍୍ୟାଙ୍କ",
    vendorDashboard: "ବିକ୍ରେତା ଡ୍ୟାସବୋର୍ଡ",
    submitReport: "ରିପୋର୍ଟ ଦାଖଲ କରନ୍ତୁ",
    rankings: "ର‍୍ୟାଙ୍କିଂ",
    reportStallStatus: "ଷ୍ଟଲ୍ ସ୍ଥିତି ରିପୋର୍ଟ କରନ୍ତୁ",
    reportStallStatusDesc: "ସ୍ଥିତି ଚୟନ କରନ୍ତୁ ଏବଂ ଫଟୋ ଅପଲୋଡ୍ କରନ୍ତୁ — ମ୍ୟୁନିସିପାଲ ଅଧିକାରୀ ସମୀକ୍ଷା କରିବେ।",
    stallNumber: "ଷ୍ଟଲ୍ ନମ୍ବର",
    marketArea: "ବଜାର ଅଞ୍ଚଳ",
    selectArea: "ଅଞ୍ଚଳ ଚୟନ କରନ୍ତୁ...",
    currentStatus: "ବର୍ତ୍ତମାନ ସ୍ଥିତି",
    clean: "ପରିଷ୍କାର",
    needsCleaning: "ସଫେଇ ଦରକାର",
    overflowing: "ଓଭରଫ୍ଲୋ",
    comments: "ମନ୍ତବ୍ୟ",
    anyNotes: "କୌଣସି ନୋଟ୍...",
    photoRequired: "ଫଟୋ ଦରକାର — ଅପଲୋଡ୍ କରିବାକୁ କ୍ଲିକ୍ କରନ୍ତୁ",
    mySubmissions: "ମୋର ଦାଖଲ",
    noPhotosYet: "ଏପର୍ଯ୍ୟନ୍ତ ଫଟୋ ନାହିଁ",
    pending: "ବାକି",
    reviewed: "ସମୀକ୍ଷିତ",
    cleaned: "ପରିଷ୍କାର ହୋଇଛି",
    weeklyVendorRankings: "ସାପ୍ତାହିକ ବିକ୍ରେତା ର‍୍ୟାଙ୍କିଂ",
    pointsEarned: "ଏହି ସପ୍ତାହରେ ଅର୍ଜିତ ପଏଣ୍ଟ",
    cleanReports: "ପରିଷ୍କାର ରିପୋର୍ଟ",
    municipalityDashboard: "ମ୍ୟୁନିସିପାଲିଟି ଡ୍ୟାସବୋର୍ଡ",
    monitorManage: "ବଜାର ପରିଷ୍କାରତା ନିରୀକ୍ଷଣ ଏବଂ ପରିଚାଳନା କରନ୍ତୁ",
    awaitingReview: "ସମୀକ୍ଷା ପାଇଁ ଅପେକ୍ଷା",
    underAction: "କାର୍ଯ୍ୟରେ",
    completed: "ସମ୍ପୂର୍ଣ୍ଣ",
    totalVendors: "ମୋଟ ବିକ୍ରେତା",
    registered: "ପଞ୍ଜୀକୃତ",
    photoReview: "ଫଟୋ ସମୀକ୍ଷା",
    vendorRankings: "ବିକ୍ରେତା ର‍୍ୟାଙ୍କିଂ",
    marketPhotos: "ବଜାର ଫଟୋ",
    reviewManagePhotos: "ଦାଖଲ ହୋଇଥିବା ଫଟୋ ସମୀକ୍ଷା ଏବଂ ପରିଚାଳନା କରନ୍ତୁ",
    filterByStatus: "ସ୍ଥିତି ଅନୁଯାୟୀ ଫିଲ୍ଟର୍ କରନ୍ତୁ",
    allPhotos: "ସମସ୍ତ ଫଟୋ",
    filterByArea: "ଅଞ୍ଚଳ ଅନୁଯାୟୀ ଫିଲ୍ଟର୍ କରନ୍ତୁ",
    allAreas: "ସମସ୍ତ ଅଞ୍ଚଳ",
    vendor: "ବିକ୍ରେତା",
    uploaded: "ଅପଲୋଡ୍ ହୋଇଛି",
    score: "ସ୍କୋର୍",
    markAsReviewed: "ସମୀକ୍ଷିତ ଭାବେ ଚିହ୍ନିତ କରନ୍ତୁ",
    markAsCleaned: "ପରିଷ୍କାର ଭାବେ ଚିହ୍ନିତ କରନ୍ତୁ",
    noPhotosSubmitted: "ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ଫଟୋ ଦାଖଲ ହୋଇନାହିଁ।",
    vendorsRankedByPoints: "ଏହି ସପ୍ତାହରେ ଅର୍ଜିତ ମୋଟ ପଏଣ୍ଟ ଅନୁଯାୟୀ ବିକ୍ରେତାମାନେ ର‍୍ୟାଙ୍କ ହୋଇଛନ୍ତି",
    photos: "ଫଟୋ",
    points: "ପଏଣ୍ଟ",
    vegetablesSection: "ପନିପରିବା ବିଭାଗ",
    fruitsSection: "ଫଳ ବିଭାଗ",
    flowerMarket: "ଫୁଲ ବଜାର",
    fishMarket: "ମାଛ ବଜାର",
    meatMarket: "ମାଂସ ବଜାର",
    pathway: "ରାସ୍ତା",
    dustbinZone: "ଡଷ୍ଟବିନ୍ ଜୋନ୍",
    other: "ଅନ୍ୟ",
    stallPlaceholder: "ଯେପରି, A-12",
    uploadSuccess: "ଧନ୍ୟବାଦ — ଆପଣଙ୍କ ରିପୋର୍ଟ ରେକର୍ଡ ହୋଇଛି। ମ୍ୟୁନିସିପାଲ ସମୀକ୍ଷା ବାକି।",
    uploadError: "ଫଟୋ ଅପଲୋଡ୍ କରିବାରେ ତ୍ରୁଟି",
    pleaseUploadImage: "ଦୟାକରି ଏକ ଚିତ୍ର ଫାଇଲ୍ ଅପଲୋଡ୍ କରନ୍ତୁ",
    fileSizeLimit: "ଫାଇଲ୍ ଆକାର 5MB ଠାରୁ କମ୍ ହେବା ଉଚିତ୍",
    noAreaSpecified: "ଅଞ୍ଚଳ ନିର୍ଦ୍ଦିଷ୍ଟ ନାହିଁ",
    pts: "ପଏଣ୍ଟ",
    pt: "ପଏଣ୍ଟ",
    unknownMarket: "ଅଜଣା ବଜାର",
    unknownVendor: "ଅଜଣା",
    failedToUpdateStatus: "ସ୍ଥିତି ଅପଡେଟ୍ କରିବାରେ ବିଫଳ",
    statusUpdatedTo: "ସ୍ଥିତି ଅପଡେଟ୍ ହେଲା",
    photoMarkedCleaned: "ଫଟୋ ପରିଷ୍କାର ଭାବେ ଚିହ୍ନିତ — ବିକ୍ରେତାଙ୍କୁ +1 ପଏଣ୍ଟ",
    photoMarkedReviewed: "ଫଟୋ ସମୀକ୍ଷିତ ଭାବେ ଚିହ୍ନିତ — କୌଣସି ପଏଣ୍ଟ ନାହିଁ",
    failedToMarkPhoto: "ଫଟୋ ଚିହ୍ନିତ କରିବାରେ ବିଫଳ",
    failedToLoadRankings: "ର‍୍ୟାଙ୍କିଂ ଲୋଡ୍ କରିବାରେ ବିଫଳ",
    failedToUpdateRankings: "ର‍୍ୟାଙ୍କିଂ ଅପଡେଟ୍ କରିବାରେ ବିଫଳ",
    loading: "ଲୋଡ୍ ହେଉଛି...",
    loadMore: "ଅଧିକ ଲୋଡ୍ କରନ୍ତୁ",
    noInternet: "ଇଣ୍ଟରନେଟ୍ ସଂଯୋଗ ନାହିଁ",
    uploadRetrying: "ଅପଲୋଡ୍ ପୁନଃପ୍ରୟାସ ହେଉଛି...",
    uploadQueued: "ଅପଲୋଡ୍ କ୍ୟୁରେ ଅଛି",
    uploadFailed: "ଅପଲୋଡ୍ ବିଫଳ",
    retryUpload: "ପୁନଃପ୍ରୟାସ କରନ୍ତୁ",
    retryAll: "ସବୁ ପୁନଃପ୍ରୟାସ କରନ୍ତୁ",
    uploadingPhoto: "ଫଟୋ ଅପଲୋଡ୍ ହେଉଛି...",
    queuedUploads: "ଅପଲୋଡ୍ କ୍ୟୁରେ ଅଛି",
    failedUploads: "ଅପଲୋଡ୍ ବିଫଳ ହେଲା",
    dismiss: "ଖାରଜ କରନ୍ତୁ",
    offlineMode: "ଅଫଲାଇନ୍ ମୋଡ୍",
    willRetryWhenOnline: "ଅନଲାଇନ୍ ହେଲେ ପୁନଃପ୍ରୟାସ ହେବ",
    serverUnavailable: "ସର୍ଭର ଉପಲବ୍ଧ ନାହିଁ",
    retryingAutomatically: "ସ୍ୱୟଂଚାଳିତ ଭାବରେ ପୁନଃପ୍ରୟାସ ହେଉଛି...",
    retryCount: "ପୁନଃପ୍ରୟାସ",
    myReviews: "ମୋର ସମୀକ୍ଷାଗୁଡ଼ିକ",
    noPendingPhotos: "ସମୀକ୍ଷା କରିବାକୁ କୌଣସି ବାକି ଫଟୋ ନାହିଁ",
    noReviewsYet: "ଆପଣ ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ଫଟୋ ସମୀକ୍ଷା କରିନାହାଁନ୍ତି",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("app-language");
    return (saved as Language) || "en";
  });

  useEffect(() => {
    localStorage.setItem("app-language", language);
  }, [language]);

  const t = translations[language];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
