// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Fall back to placeholder values when env vars are not set so the app
// doesn't crash on import (all API calls will simply fail gracefully).
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL || "https://placeholder.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "placeholder-anon-key";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Required for production (Vercel): PKCE code exchange after email
    // confirmation must be explicitly enabled so the auth code in the
    // redirect URL (?code=...) is properly exchanged for a session.
    detectSessionInUrl: true,
    flowType: 'pkce',
  }
});
